// Code generated by gnark DO NOT EDIT

struct PlonkQuotientParams {
  count: u32,       // points per coset (small domain size n)
  blind_count: u32, // coefficients per blinding polynomial
  coset_count: u32, // rho = large domain size / n
  coset_base: u32,  // index of the coset evaluated by this dispatch
  log_total: u32,   // log2(rho * n)
  _pad0: u32,
  _pad1: u32,
  _pad2: u32,
}

override COMMITMENT_COUNT: u32 = 0u;

const PLONK_FR_WORDS: u32 = 8u;
const PLONK_BLIND_COUNT: u32 = 4u;
const PLONK_SCALAR_COUNT: u32 = 7u;

// dynamic vectors: L, R, O, Z, Qk, then the COMMITMENT_COUNT committed values
const PLONK_VEC_L: u32 = 0u;
const PLONK_VEC_R: u32 = 1u;
const PLONK_VEC_O: u32 = 2u;
const PLONK_VEC_Z: u32 = 3u;
const PLONK_VEC_QK: u32 = 4u;
const PLONK_DYNAMIC_BASE_COUNT: u32 = 5u;

// static vectors: Ql, Qr, Qm, Qo, S1, S2, S3, then the COMMITMENT_COUNT selectors Qcp
const PLONK_VEC_QL: u32 = 0u;
const PLONK_VEC_QR: u32 = 1u;
const PLONK_VEC_QM: u32 = 2u;
const PLONK_VEC_QO: u32 = 3u;
const PLONK_VEC_S1: u32 = 4u;
const PLONK_VEC_S2: u32 = 5u;
const PLONK_VEC_S3: u32 = 6u;
const PLONK_STATIC_BASE_COUNT: u32 = 7u;

const PLONK_BLIND_L: u32 = 0u;
const PLONK_BLIND_R: u32 = 1u;
const PLONK_BLIND_O: u32 = 2u;
const PLONK_BLIND_Z: u32 = 3u;

const PLONK_SCALAR_COSET: u32 = 0u;
const PLONK_SCALAR_LAGRANGE_SCALE: u32 = 1u;
const PLONK_SCALAR_CS: u32 = 2u;
const PLONK_SCALAR_CSS: u32 = 3u;
const PLONK_SCALAR_BETA: u32 = 4u;
const PLONK_SCALAR_GAMMA: u32 = 5u;
const PLONK_SCALAR_ALPHA: u32 = 6u;

@group(0) @binding(0) var<storage, read> plonk_dynamic: array<u32>;      // evaluations on the coset
@group(0) @binding(1) var<storage, read> plonk_static: array<u32>;       // evaluations on the coset
@group(0) @binding(2) var<storage, read> plonk_twiddles: array<u32>;     // ω^i of the small domain
@group(0) @binding(3) var<storage, read> plonk_denominators: array<u32>; // 1/(s·ω^i − 1) for this coset
@group(0) @binding(4) var<storage, read> plonk_blinds: array<u32>;       // all cosets
@group(0) @binding(5) var<storage, read> plonk_scalars: array<u32>;      // all cosets
@group(0) @binding(6) var<storage, read_write> plonk_output: array<u32>; // large domain, bit-reversed
@group(0) @binding(7) var<uniform> plonk_params: PlonkQuotientParams;

fn plonk_load_dynamic(vector: u32, index: u32) -> Fr {
  let base = (vector * plonk_params.count + index) * PLONK_FR_WORDS;
  var z: Fr;
  z.limbs[0] = plonk_dynamic[base + 0u];
  z.limbs[1] = plonk_dynamic[base + 1u];
  z.limbs[2] = plonk_dynamic[base + 2u];
  z.limbs[3] = plonk_dynamic[base + 3u];
  z.limbs[4] = plonk_dynamic[base + 4u];
  z.limbs[5] = plonk_dynamic[base + 5u];
  z.limbs[6] = plonk_dynamic[base + 6u];
  z.limbs[7] = plonk_dynamic[base + 7u];
  return z;
}

fn plonk_load_static(vector: u32, index: u32) -> Fr {
  let base = (vector * plonk_params.count + index) * PLONK_FR_WORDS;
  var z: Fr;
  z.limbs[0] = plonk_static[base + 0u];
  z.limbs[1] = plonk_static[base + 1u];
  z.limbs[2] = plonk_static[base + 2u];
  z.limbs[3] = plonk_static[base + 3u];
  z.limbs[4] = plonk_static[base + 4u];
  z.limbs[5] = plonk_static[base + 5u];
  z.limbs[6] = plonk_static[base + 6u];
  z.limbs[7] = plonk_static[base + 7u];
  return z;
}

fn plonk_load_twiddle(index: u32) -> Fr {
  let base = index * PLONK_FR_WORDS;
  var z: Fr;
  z.limbs[0] = plonk_twiddles[base + 0u];
  z.limbs[1] = plonk_twiddles[base + 1u];
  z.limbs[2] = plonk_twiddles[base + 2u];
  z.limbs[3] = plonk_twiddles[base + 3u];
  z.limbs[4] = plonk_twiddles[base + 4u];
  z.limbs[5] = plonk_twiddles[base + 5u];
  z.limbs[6] = plonk_twiddles[base + 6u];
  z.limbs[7] = plonk_twiddles[base + 7u];
  return z;
}

fn plonk_load_denominator(index: u32) -> Fr {
  let base = index * PLONK_FR_WORDS;
  var z: Fr;
  z.limbs[0] = plonk_denominators[base + 0u];
  z.limbs[1] = plonk_denominators[base + 1u];
  z.limbs[2] = plonk_denominators[base + 2u];
  z.limbs[3] = plonk_denominators[base + 3u];
  z.limbs[4] = plonk_denominators[base + 4u];
  z.limbs[5] = plonk_denominators[base + 5u];
  z.limbs[6] = plonk_denominators[base + 6u];
  z.limbs[7] = plonk_denominators[base + 7u];
  return z;
}

fn plonk_load_blind(poly: u32, index: u32) -> Fr {
  let base = (((plonk_params.coset_base * PLONK_BLIND_COUNT + poly) * plonk_params.blind_count) + index) * PLONK_FR_WORDS;
  var z: Fr;
  z.limbs[0] = plonk_blinds[base + 0u];
  z.limbs[1] = plonk_blinds[base + 1u];
  z.limbs[2] = plonk_blinds[base + 2u];
  z.limbs[3] = plonk_blinds[base + 3u];
  z.limbs[4] = plonk_blinds[base + 4u];
  z.limbs[5] = plonk_blinds[base + 5u];
  z.limbs[6] = plonk_blinds[base + 6u];
  z.limbs[7] = plonk_blinds[base + 7u];
  return z;
}

fn plonk_load_scalar(index: u32) -> Fr {
  let base = ((plonk_params.coset_base * PLONK_SCALAR_COUNT) + index) * PLONK_FR_WORDS;
  var z: Fr;
  z.limbs[0] = plonk_scalars[base + 0u];
  z.limbs[1] = plonk_scalars[base + 1u];
  z.limbs[2] = plonk_scalars[base + 2u];
  z.limbs[3] = plonk_scalars[base + 3u];
  z.limbs[4] = plonk_scalars[base + 4u];
  z.limbs[5] = plonk_scalars[base + 5u];
  z.limbs[6] = plonk_scalars[base + 6u];
  z.limbs[7] = plonk_scalars[base + 7u];
  return z;
}

fn plonk_store(index: u32, value: Fr) {
  // position of (coset, index) in the bit-reversed large domain
  let position = reverseBits(plonk_params.coset_count * index + plonk_params.coset_base) >> (32u - plonk_params.log_total);
  let base = position * PLONK_FR_WORDS;
  plonk_output[base + 0u] = value.limbs[0];
  plonk_output[base + 1u] = value.limbs[1];
  plonk_output[base + 2u] = value.limbs[2];
  plonk_output[base + 3u] = value.limbs[3];
  plonk_output[base + 4u] = value.limbs[4];
  plonk_output[base + 5u] = value.limbs[5];
  plonk_output[base + 6u] = value.limbs[6];
  plonk_output[base + 7u] = value.limbs[7];
}

// Horner evaluation of a blinding polynomial at `point`.
fn plonk_eval_blind(poly: u32, point: Fr) -> Fr {
  var res = fr_zero();
  var i = plonk_params.blind_count;
  loop {
    if (i == 0u) {
      break;
    }
    i = i - 1u;
    res = fr_add(fr_mul(res, point), plonk_load_blind(poly, i));
  }
  return res;
}

fn plonk_evaluate_quotient(index: u32) -> Fr {
  let twiddle = plonk_load_twiddle(index);
  let next_index = (index + 1u) % plonk_params.count;
  let next_twiddle = plonk_load_twiddle(next_index);

  var l = fr_add(plonk_load_dynamic(PLONK_VEC_L, index), plonk_eval_blind(PLONK_BLIND_L, twiddle));
  var r = fr_add(plonk_load_dynamic(PLONK_VEC_R, index), plonk_eval_blind(PLONK_BLIND_R, twiddle));
  var o = fr_add(plonk_load_dynamic(PLONK_VEC_O, index), plonk_eval_blind(PLONK_BLIND_O, twiddle));
  var z = fr_add(plonk_load_dynamic(PLONK_VEC_Z, index), plonk_eval_blind(PLONK_BLIND_Z, twiddle));
  let zs = fr_add(plonk_load_dynamic(PLONK_VEC_Z, next_index), plonk_eval_blind(PLONK_BLIND_Z, next_twiddle));

  // gate constraint
  var gate = fr_mul(plonk_load_static(PLONK_VEC_QL, index), l);
  gate = fr_add(gate, fr_mul(plonk_load_static(PLONK_VEC_QR, index), r));
  gate = fr_add(gate, fr_mul(fr_mul(plonk_load_static(PLONK_VEC_QM, index), l), r));
  gate = fr_add(gate, fr_mul(plonk_load_static(PLONK_VEC_QO, index), o));
  gate = fr_add(gate, plonk_load_dynamic(PLONK_VEC_QK, index));
  var commitment_index = 0u;
  loop {
    if (commitment_index >= COMMITMENT_COUNT) {
      break;
    }
    let qcp = plonk_load_static(PLONK_STATIC_BASE_COUNT + commitment_index, index);
    let committed = plonk_load_dynamic(PLONK_DYNAMIC_BASE_COUNT + commitment_index, index);
    gate = fr_add(gate, fr_mul(qcp, committed));
    commitment_index = commitment_index + 1u;
  }

  // ordering (copy) constraint
  let beta = plonk_load_scalar(PLONK_SCALAR_BETA);
  let gamma = plonk_load_scalar(PLONK_SCALAR_GAMMA);
  let alpha = plonk_load_scalar(PLONK_SCALAR_ALPHA);
  let id = fr_mul(fr_mul(twiddle, plonk_load_scalar(PLONK_SCALAR_COSET)), beta);

  var a = fr_add(fr_add(gamma, l), id);
  var b = fr_add(fr_add(fr_mul(id, plonk_load_scalar(PLONK_SCALAR_CS)), r), gamma);
  var c = fr_add(fr_add(fr_mul(id, plonk_load_scalar(PLONK_SCALAR_CSS)), o), gamma);
  let right = fr_mul(fr_mul(fr_mul(a, b), c), z);

  a = fr_add(fr_add(fr_mul(plonk_load_static(PLONK_VEC_S1, index), beta), l), gamma);
  b = fr_add(fr_add(fr_mul(plonk_load_static(PLONK_VEC_S2, index), beta), r), gamma);
  c = fr_add(fr_add(fr_mul(plonk_load_static(PLONK_VEC_S3, index), beta), o), gamma);
  let left = fr_mul(fr_mul(fr_mul(a, b), c), zs);

  let ordering = fr_sub(left, right);

  // (Z − 1)·L₁ on the coset
  let lone = fr_mul(plonk_load_scalar(PLONK_SCALAR_LAGRANGE_SCALE), plonk_load_denominator(index));
  var local = fr_mul(fr_sub(z, fr_one()), lone);

  // Horner in alpha: gate + alpha*(ordering + alpha*local)
  local = fr_add(fr_mul(local, alpha), ordering);
  return fr_add(fr_mul(local, alpha), gate);
}

override WORKGROUP_SIZE: u32 = 64;

@compute @workgroup_size(WORKGROUP_SIZE)
fn fr_plonk_quotient_main(@builtin(global_invocation_id) id: vec3<u32>) {
  let i = id.x;
  if (i >= plonk_params.count) {
    return;
  }
  plonk_store(i, plonk_evaluate_quotient(i));
}
