// Code generated by gnark DO NOT EDIT

struct Fr {
  limbs: array<u32, 8>,
}

// Every opcode may additionally multiply its result by `scalar` (Montgomery
// multiplication) when `scale` is non-zero, which folds "scale by a
// constant" and "convert to/from Montgomery form" into the same pass.
struct Params {
  count: u32,
  opcode: u32,
  // BIT_REVERSE_COPY / POWER: number of significant index bits.
  log_count: u32,
  // BIT_REVERSE_COPY / MUL_FACTORS: length of each vector when the buffer
  // holds several (0 = a single vector).
  vector_size: u32,
  scale: u32,
  _pad0: u32,
  _pad1: u32,
  _pad2: u32,
  scalar: array<vec4<u32>, 2>,
}

const FR_VECTOR_OP_COPY: u32 = 0u;
const FR_VECTOR_OP_ADD: u32 = 1u;
const FR_VECTOR_OP_SUB: u32 = 2u;
// output[i] = values[i] * aux[i mod vector_size]
const FR_VECTOR_OP_MUL_FACTORS: u32 = 3u;
// output[i] = values[reverse_bits(i)] within each vector
const FR_VECTOR_OP_BIT_REVERSE_COPY: u32 = 4u;
// output[i] = scalar^i (scalar in Montgomery form); the scale flag is ignored.
const FR_VECTOR_OP_POWER: u32 = 5u;

const FR_LIMB16_MASK: u32 = 0xffffu;
const FR_QINV_NEG_16: u32 = 0xffffu;

const FR_MODULUS32: array<u32, 8> = array<u32, 8>(
  0xf0000001u,
  0x43e1f593u,
  0x79b97091u,
  0x2833e848u,
  0x8181585du,
  0xb85045b6u,
  0xe131a029u,
  0x30644e72u,
);

const FR_MODULUS16: array<u32, 16> = array<u32, 16>(
  0x0001u, 0xf000u,
  0xf593u, 0x43e1u,
  0x7091u, 0x79b9u,
  0xe848u, 0x2833u,
  0x585du, 0x8181u,
  0x45b6u, 0xb850u,
  0xa029u, 0xe131u,
  0x4e72u, 0x3064u,
);

@group(0) @binding(0) var<storage, read> input_values: array<u32>;
@group(0) @binding(1) var<storage, read> input_aux: array<u32>;
@group(0) @binding(2) var<storage, read_write> output: array<u32>;
@group(0) @binding(3) var<uniform> params: Params;

fn fr_zero() -> Fr {
  var z: Fr;
  z.limbs[0] = 0u;
  z.limbs[1] = 0u;
  z.limbs[2] = 0u;
  z.limbs[3] = 0u;
  z.limbs[4] = 0u;
  z.limbs[5] = 0u;
  z.limbs[6] = 0u;
  z.limbs[7] = 0u;
  return z;
}

fn fr_one() -> Fr {
  var z: Fr;
  z.limbs[0] = 0x4ffffffbu;
  z.limbs[1] = 0xac96341cu;
  z.limbs[2] = 0x9f60cd29u;
  z.limbs[3] = 0x36fc7695u;
  z.limbs[4] = 0x7879462eu;
  z.limbs[5] = 0x666ea36fu;
  z.limbs[6] = 0x9a07df2fu;
  z.limbs[7] = 0x0e0a77c1u;
  return z;
}

fn fr_one_regular() -> Fr {
  var z = fr_zero();
  z.limbs[0] = 1u;
  return z;
}

fn fr_rsquare_regular() -> Fr {
  var z: Fr;
  z.limbs[0] = 0xae216da7u;
  z.limbs[1] = 0x1bb8e645u;
  z.limbs[2] = 0xe35c59e3u;
  z.limbs[3] = 0x53fe3ab1u;
  z.limbs[4] = 0x53bb8085u;
  z.limbs[5] = 0x8c49833du;
  z.limbs[6] = 0x7f4e44a5u;
  z.limbs[7] = 0x0216d0b1u;
  return z;
}

fn fr_predicate(value: bool) -> Fr {
  let one = fr_one();
  var z: Fr;
  z.limbs[0] = select(0u, one.limbs[0], value);
  z.limbs[1] = select(0u, one.limbs[1], value);
  z.limbs[2] = select(0u, one.limbs[2], value);
  z.limbs[3] = select(0u, one.limbs[3], value);
  z.limbs[4] = select(0u, one.limbs[4], value);
  z.limbs[5] = select(0u, one.limbs[5], value);
  z.limbs[6] = select(0u, one.limbs[6], value);
  z.limbs[7] = select(0u, one.limbs[7], value);
  return z;
}

fn adc(a: u32, b: u32, carry: u32) -> vec2<u32> {
  let sum0 = a + b;
  let sum1 = sum0 + carry;
  return vec2<u32>(sum1, u32(sum0 < a) | u32(sum1 < sum0));
}

fn sbb(a: u32, b: u32, borrow: u32) -> vec2<u32> {
  let diff0 = a - b;
  let diff1 = diff0 - borrow;
  return vec2<u32>(diff1, u32(a < b) | u32(diff1 > diff0));
}

fn fr_is_zero(x: Fr) -> bool {
  return (x.limbs[0] | x.limbs[1] | x.limbs[2] | x.limbs[3] |
    x.limbs[4] | x.limbs[5] | x.limbs[6] | x.limbs[7]) == 0u;
}

fn fr_equal(x: Fr, y: Fr) -> bool {
  return (x.limbs[0] == y.limbs[0]) &&
    (x.limbs[1] == y.limbs[1]) &&
    (x.limbs[2] == y.limbs[2]) &&
    (x.limbs[3] == y.limbs[3]) &&
    (x.limbs[4] == y.limbs[4]) &&
    (x.limbs[5] == y.limbs[5]) &&
    (x.limbs[6] == y.limbs[6]) &&
    (x.limbs[7] == y.limbs[7]);
}

// x + y mod q: z = x + y, t = z - q; the result is t when the addition
// carried or the subtraction did not borrow (z >= q), else z.
fn fr_add(x: Fr, y: Fr) -> Fr {
  var z: Fr;
  var t: Fr;
  var lane = adc(x.limbs[0], y.limbs[0], 0u);
  z.limbs[0] = lane.x;
  lane = adc(x.limbs[1], y.limbs[1], lane.y);
  z.limbs[1] = lane.x;
  lane = adc(x.limbs[2], y.limbs[2], lane.y);
  z.limbs[2] = lane.x;
  lane = adc(x.limbs[3], y.limbs[3], lane.y);
  z.limbs[3] = lane.x;
  lane = adc(x.limbs[4], y.limbs[4], lane.y);
  z.limbs[4] = lane.x;
  lane = adc(x.limbs[5], y.limbs[5], lane.y);
  z.limbs[5] = lane.x;
  lane = adc(x.limbs[6], y.limbs[6], lane.y);
  z.limbs[6] = lane.x;
  lane = adc(x.limbs[7], y.limbs[7], lane.y);
  z.limbs[7] = lane.x;
  let carry = lane.y;
  lane = sbb(z.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(z.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(z.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(z.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(z.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(z.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(z.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(z.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  let use_t = (carry != 0u) || (lane.y == 0u);
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  return z;
}

// x - y mod q: z = x - y, t = z + q; the result is t when the subtraction
// borrowed, else z.
fn fr_sub(x: Fr, y: Fr) -> Fr {
  var z: Fr;
  var t: Fr;
  var lane = sbb(x.limbs[0], y.limbs[0], 0u);
  z.limbs[0] = lane.x;
  lane = sbb(x.limbs[1], y.limbs[1], lane.y);
  z.limbs[1] = lane.x;
  lane = sbb(x.limbs[2], y.limbs[2], lane.y);
  z.limbs[2] = lane.x;
  lane = sbb(x.limbs[3], y.limbs[3], lane.y);
  z.limbs[3] = lane.x;
  lane = sbb(x.limbs[4], y.limbs[4], lane.y);
  z.limbs[4] = lane.x;
  lane = sbb(x.limbs[5], y.limbs[5], lane.y);
  z.limbs[5] = lane.x;
  lane = sbb(x.limbs[6], y.limbs[6], lane.y);
  z.limbs[6] = lane.x;
  lane = sbb(x.limbs[7], y.limbs[7], lane.y);
  z.limbs[7] = lane.x;
  let use_t = lane.y != 0u;
  lane = adc(z.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = adc(z.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = adc(z.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = adc(z.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = adc(z.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = adc(z.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = adc(z.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = adc(z.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  return z;
}

// -x mod q: q - x, or zero when x is zero.
fn fr_neg(x: Fr) -> Fr {
  var t: Fr;
  var lane = sbb(FR_MODULUS32[0], x.limbs[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(FR_MODULUS32[1], x.limbs[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(FR_MODULUS32[2], x.limbs[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(FR_MODULUS32[3], x.limbs[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(FR_MODULUS32[4], x.limbs[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(FR_MODULUS32[5], x.limbs[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(FR_MODULUS32[6], x.limbs[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(FR_MODULUS32[7], x.limbs[7], lane.y);
  t.limbs[7] = lane.x;
  let nonzero = !fr_is_zero(x);
  var z: Fr;
  z.limbs[0] = select(0u, t.limbs[0], nonzero);
  z.limbs[1] = select(0u, t.limbs[1], nonzero);
  z.limbs[2] = select(0u, t.limbs[2], nonzero);
  z.limbs[3] = select(0u, t.limbs[3], nonzero);
  z.limbs[4] = select(0u, t.limbs[4], nonzero);
  z.limbs[5] = select(0u, t.limbs[5], nonzero);
  z.limbs[6] = select(0u, t.limbs[6], nonzero);
  z.limbs[7] = select(0u, t.limbs[7], nonzero);
  return z;
}

// 2x mod q: a left shift by one bit, then the same conditional subtraction
// as fr_add.
fn fr_double(x: Fr) -> Fr {
  var z: Fr;
  var t: Fr;
  z.limbs[0] = x.limbs[0] << 1u;
  z.limbs[1] = (x.limbs[1] << 1u) | (x.limbs[0] >> 31u);
  z.limbs[2] = (x.limbs[2] << 1u) | (x.limbs[1] >> 31u);
  z.limbs[3] = (x.limbs[3] << 1u) | (x.limbs[2] >> 31u);
  z.limbs[4] = (x.limbs[4] << 1u) | (x.limbs[3] >> 31u);
  z.limbs[5] = (x.limbs[5] << 1u) | (x.limbs[4] >> 31u);
  z.limbs[6] = (x.limbs[6] << 1u) | (x.limbs[5] >> 31u);
  z.limbs[7] = (x.limbs[7] << 1u) | (x.limbs[6] >> 31u);
  let carry = x.limbs[7] >> 31u;
  var lane: vec2<u32>;
  lane = sbb(z.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(z.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(z.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(z.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(z.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(z.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(z.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(z.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  let use_t = (carry != 0u) || (lane.y == 0u);
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  return z;
}

// Reduce a value in [0, 2q) to [0, q).
fn fr_normalize(x: Fr) -> Fr {
  var t: Fr;
  var z: Fr;
  var lane: vec2<u32>;
  lane = sbb(x.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(x.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(x.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(x.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(x.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(x.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(x.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(x.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  let use_t = lane.y == 0u;
  z.limbs[0] = select(x.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(x.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(x.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(x.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(x.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(x.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(x.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(x.limbs[7], t.limbs[7], use_t);
  return z;
}

// Montgomery multiplication (CIOS) over 16-bit digits: R = 2^(16*16).
// Each 16x16 partial product plus carries fits in a u32 without overflow.
// The digit loops are unrolled so the accumulator lives in registers; the
// final conditional subtraction is branch-free.
fn fr_mul(x: Fr, y: Fr) -> Fr {
  let a0 = x.limbs[0] & FR_LIMB16_MASK;
  let a1 = x.limbs[0] >> 16u;
  let a2 = x.limbs[1] & FR_LIMB16_MASK;
  let a3 = x.limbs[1] >> 16u;
  let a4 = x.limbs[2] & FR_LIMB16_MASK;
  let a5 = x.limbs[2] >> 16u;
  let a6 = x.limbs[3] & FR_LIMB16_MASK;
  let a7 = x.limbs[3] >> 16u;
  let a8 = x.limbs[4] & FR_LIMB16_MASK;
  let a9 = x.limbs[4] >> 16u;
  let a10 = x.limbs[5] & FR_LIMB16_MASK;
  let a11 = x.limbs[5] >> 16u;
  let a12 = x.limbs[6] & FR_LIMB16_MASK;
  let a13 = x.limbs[6] >> 16u;
  let a14 = x.limbs[7] & FR_LIMB16_MASK;
  let a15 = x.limbs[7] >> 16u;
  var t0 = 0u;
  var t1 = 0u;
  var t2 = 0u;
  var t3 = 0u;
  var t4 = 0u;
  var t5 = 0u;
  var t6 = 0u;
  var t7 = 0u;
  var t8 = 0u;
  var t9 = 0u;
  var t10 = 0u;
  var t11 = 0u;
  var t12 = 0u;
  var t13 = 0u;
  var t14 = 0u;
  var t15 = 0u;
  var t16 = 0u;
  var uv = 0u;
  var c = 0u;
  var m = 0u;
  for (var i = 0u; i < 8u; i = i + 1u) {
    let w = y.limbs[i];
    let b_lo = w & FR_LIMB16_MASK;
    let b_hi = w >> 16u;
    uv = t0 + a0 * b_lo;
    t0 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t1 + a1 * b_lo + c;
    t1 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + a2 * b_lo + c;
    t2 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + a3 * b_lo + c;
    t3 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + a4 * b_lo + c;
    t4 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + a5 * b_lo + c;
    t5 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + a6 * b_lo + c;
    t6 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + a7 * b_lo + c;
    t7 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + a8 * b_lo + c;
    t8 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + a9 * b_lo + c;
    t9 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + a10 * b_lo + c;
    t10 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + a11 * b_lo + c;
    t11 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + a12 * b_lo + c;
    t12 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + a13 * b_lo + c;
    t13 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + a14 * b_lo + c;
    t14 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + a15 * b_lo + c;
    t15 = uv & FR_LIMB16_MASK;
    t16 = uv >> 16u;
    m = (t0 * FR_QINV_NEG_16) & FR_LIMB16_MASK;
    // (t0 + m*q0) is 0 mod 2^16 by construction: only its carry survives.
    c = (t0 + m * FR_MODULUS16[0]) >> 16u;
    uv = t1 + m * FR_MODULUS16[1] + c;
    t0 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + m * FR_MODULUS16[2] + c;
    t1 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + m * FR_MODULUS16[3] + c;
    t2 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + m * FR_MODULUS16[4] + c;
    t3 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + m * FR_MODULUS16[5] + c;
    t4 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + m * FR_MODULUS16[6] + c;
    t5 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + m * FR_MODULUS16[7] + c;
    t6 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + m * FR_MODULUS16[8] + c;
    t7 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + m * FR_MODULUS16[9] + c;
    t8 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + m * FR_MODULUS16[10] + c;
    t9 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + m * FR_MODULUS16[11] + c;
    t10 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + m * FR_MODULUS16[12] + c;
    t11 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + m * FR_MODULUS16[13] + c;
    t12 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + m * FR_MODULUS16[14] + c;
    t13 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + m * FR_MODULUS16[15] + c;
    t14 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t16 + c;
    t15 = uv & FR_LIMB16_MASK;
    t16 = uv >> 16u;
    uv = t0 + a0 * b_hi;
    t0 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t1 + a1 * b_hi + c;
    t1 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + a2 * b_hi + c;
    t2 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + a3 * b_hi + c;
    t3 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + a4 * b_hi + c;
    t4 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + a5 * b_hi + c;
    t5 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + a6 * b_hi + c;
    t6 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + a7 * b_hi + c;
    t7 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + a8 * b_hi + c;
    t8 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + a9 * b_hi + c;
    t9 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + a10 * b_hi + c;
    t10 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + a11 * b_hi + c;
    t11 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + a12 * b_hi + c;
    t12 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + a13 * b_hi + c;
    t13 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + a14 * b_hi + c;
    t14 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + a15 * b_hi + c;
    t15 = uv & FR_LIMB16_MASK;
    t16 = uv >> 16u;
    m = (t0 * FR_QINV_NEG_16) & FR_LIMB16_MASK;
    // (t0 + m*q0) is 0 mod 2^16 by construction: only its carry survives.
    c = (t0 + m * FR_MODULUS16[0]) >> 16u;
    uv = t1 + m * FR_MODULUS16[1] + c;
    t0 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + m * FR_MODULUS16[2] + c;
    t1 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + m * FR_MODULUS16[3] + c;
    t2 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + m * FR_MODULUS16[4] + c;
    t3 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + m * FR_MODULUS16[5] + c;
    t4 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + m * FR_MODULUS16[6] + c;
    t5 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + m * FR_MODULUS16[7] + c;
    t6 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + m * FR_MODULUS16[8] + c;
    t7 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + m * FR_MODULUS16[9] + c;
    t8 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + m * FR_MODULUS16[10] + c;
    t9 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + m * FR_MODULUS16[11] + c;
    t10 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + m * FR_MODULUS16[12] + c;
    t11 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + m * FR_MODULUS16[13] + c;
    t12 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + m * FR_MODULUS16[14] + c;
    t13 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + m * FR_MODULUS16[15] + c;
    t14 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t16 + c;
    t15 = uv & FR_LIMB16_MASK;
    t16 = uv >> 16u;
  }

  var z: Fr;
  z.limbs[0] = t0 | (t1 << 16u);
  z.limbs[1] = t2 | (t3 << 16u);
  z.limbs[2] = t4 | (t5 << 16u);
  z.limbs[3] = t6 | (t7 << 16u);
  z.limbs[4] = t8 | (t9 << 16u);
  z.limbs[5] = t10 | (t11 << 16u);
  z.limbs[6] = t12 | (t13 << 16u);
  z.limbs[7] = t14 | (t15 << 16u);
  var t: Fr;
  var lane: vec2<u32>;
  lane = sbb(z.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(z.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(z.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(z.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(z.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(z.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(z.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(z.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  let use_t = (t16 != 0u) || (lane.y == 0u);
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  return z;
}

fn fr_square(x: Fr) -> Fr {
  return fr_mul(x, x);
}

fn fr_from_uniform(words: array<vec4<u32>, 2>) -> Fr {
  var z: Fr;
  z.limbs[0] = words[0][0];
  z.limbs[1] = words[0][1];
  z.limbs[2] = words[0][2];
  z.limbs[3] = words[0][3];
  z.limbs[4] = words[1][0];
  z.limbs[5] = words[1][1];
  z.limbs[6] = words[1][2];
  z.limbs[7] = words[1][3];
  return z;
}

fn fr_load_from(buffer_kind: u32, index: u32) -> Fr {
  let base = index * 8u;
  var z: Fr;
  if (buffer_kind == 0u) {
    z.limbs[0] = input_values[base + 0u];
    z.limbs[1] = input_values[base + 1u];
    z.limbs[2] = input_values[base + 2u];
    z.limbs[3] = input_values[base + 3u];
    z.limbs[4] = input_values[base + 4u];
    z.limbs[5] = input_values[base + 5u];
    z.limbs[6] = input_values[base + 6u];
    z.limbs[7] = input_values[base + 7u];
    return z;
  }
  z.limbs[0] = input_aux[base + 0u];
  z.limbs[1] = input_aux[base + 1u];
  z.limbs[2] = input_aux[base + 2u];
  z.limbs[3] = input_aux[base + 3u];
  z.limbs[4] = input_aux[base + 4u];
  z.limbs[5] = input_aux[base + 5u];
  z.limbs[6] = input_aux[base + 6u];
  z.limbs[7] = input_aux[base + 7u];
  return z;
}

fn fr_store(index: u32, value: Fr) {
  let base = index * 8u;
  output[base + 0u] = value.limbs[0];
  output[base + 1u] = value.limbs[1];
  output[base + 2u] = value.limbs[2];
  output[base + 3u] = value.limbs[3];
  output[base + 4u] = value.limbs[4];
  output[base + 5u] = value.limbs[5];
  output[base + 6u] = value.limbs[6];
  output[base + 7u] = value.limbs[7];
}

// scalar^exponent by square-and-multiply over the low `log_count` bits.
fn fr_power(base: Fr, exponent: u32, bits: u32) -> Fr {
  var acc = fr_one();
  var sq = base;
  for (var bit = 0u; bit < bits; bit = bit + 1u) {
    let product = fr_mul(acc, sq);
    let take = ((exponent >> bit) & 1u) != 0u;
    acc.limbs[0] = select(acc.limbs[0], product.limbs[0], take);
    acc.limbs[1] = select(acc.limbs[1], product.limbs[1], take);
    acc.limbs[2] = select(acc.limbs[2], product.limbs[2], take);
    acc.limbs[3] = select(acc.limbs[3], product.limbs[3], take);
    acc.limbs[4] = select(acc.limbs[4], product.limbs[4], take);
    acc.limbs[5] = select(acc.limbs[5], product.limbs[5], take);
    acc.limbs[6] = select(acc.limbs[6], product.limbs[6], take);
    acc.limbs[7] = select(acc.limbs[7], product.limbs[7], take);
    sq = fr_mul(sq, sq);
  }
  return acc;
}

fn fr_dispatch(index: u32) -> Fr {
  let vector_mask = select(0xffffffffu, params.vector_size - 1u, params.vector_size != 0u);
  if (params.opcode == FR_VECTOR_OP_COPY) {
    return fr_load_from(0u, index);
  }
  if (params.opcode == FR_VECTOR_OP_ADD) {
    return fr_add(fr_load_from(0u, index), fr_load_from(1u, index));
  }
  if (params.opcode == FR_VECTOR_OP_SUB) {
    return fr_sub(fr_load_from(0u, index), fr_load_from(1u, index));
  }
  if (params.opcode == FR_VECTOR_OP_MUL_FACTORS) {
    return fr_mul(fr_load_from(0u, index), fr_load_from(1u, index & vector_mask));
  }
  if (params.opcode == FR_VECTOR_OP_BIT_REVERSE_COPY) {
    let lane = index & vector_mask;
    let reversed = reverseBits(lane) >> min(32u - params.log_count, 31u);
    return fr_load_from(0u, (index - lane) + reversed);
  }
  if (params.opcode == FR_VECTOR_OP_POWER) {
    return fr_power(fr_from_uniform(params.scalar), index, params.log_count);
  }
  return fr_zero();
}

override WORKGROUP_SIZE: u32 = 64;

@compute @workgroup_size(WORKGROUP_SIZE)
fn fr_vector_main(@builtin(global_invocation_id) id: vec3<u32>) {
  let i = id.x;
  if (i >= params.count) {
    return;
  }
  var value = fr_dispatch(i);
  if (params.scale != 0u && params.opcode != FR_VECTOR_OP_POWER) {
    value = fr_mul(value, fr_from_uniform(params.scalar));
  }
  fr_store(i, value);
}
