// Code generated by gnark DO NOT EDIT

fn fp_load_from(buffer_kind: u32, base: u32) -> Fp {
  var z: Fp;
  if (buffer_kind == 0u) {
    z.limbs[0] = input_a[base + 0u];
    z.limbs[1] = input_a[base + 1u];
    z.limbs[2] = input_a[base + 2u];
    z.limbs[3] = input_a[base + 3u];
    z.limbs[4] = input_a[base + 4u];
    z.limbs[5] = input_a[base + 5u];
    z.limbs[6] = input_a[base + 6u];
    z.limbs[7] = input_a[base + 7u];
    return z;
  }
  z.limbs[0] = input_b[base + 0u];
  z.limbs[1] = input_b[base + 1u];
  z.limbs[2] = input_b[base + 2u];
  z.limbs[3] = input_b[base + 3u];
  z.limbs[4] = input_b[base + 4u];
  z.limbs[5] = input_b[base + 5u];
  z.limbs[6] = input_b[base + 6u];
  z.limbs[7] = input_b[base + 7u];
  return z;
}

fn fp_store(base: u32, value: Fp) {
  output[base + 0u] = value.limbs[0];
  output[base + 1u] = value.limbs[1];
  output[base + 2u] = value.limbs[2];
  output[base + 3u] = value.limbs[3];
  output[base + 4u] = value.limbs[4];
  output[base + 5u] = value.limbs[5];
  output[base + 6u] = value.limbs[6];
  output[base + 7u] = value.limbs[7];
}

fn fp2_load_from(buffer_kind: u32, base: u32) -> Fp2 {
  var z: Fp2;
  z.c0 = fp_load_from(buffer_kind, base);
  z.c1 = fp_load_from(buffer_kind, base + 8u);
  return z;
}

fn g2_load_from(buffer_kind: u32, index: u32) -> G2Point {
  let base = index * 48u;
  var p: G2Point;
  p.x = fp2_load_from(buffer_kind, base + 0u);
  p.y = fp2_load_from(buffer_kind, base + 16u);
  p.z = fp2_load_from(buffer_kind, base + 32u);
  return p;
}

// Load affine base `index` (x, y) from input_a; z becomes the infinity flag
// (one for a finite point, zero for the all-zero encoding of infinity).
fn g2_load_affine(index: u32) -> G2Point {
  let base = index * 32u;
  var p: G2Point;
  p.x = fp2_load_from(0u, base + 0u);
  p.y = fp2_load_from(0u, base + 16u);
  p.z = fp2_zero();
  if (!(fp2_is_zero(p.x) && fp2_is_zero(p.y))) {
    p.z = fp2_one();
  }
  return p;
}

fn fp2_store(base: u32, value: Fp2) {
  fp_store(base, value.c0);
  fp_store(base + 8u, value.c1);
}

fn g2_store(index: u32, value: G2Point) {
  let base = index * 48u;
  fp2_store(base + 0u, value.x);
  fp2_store(base + 16u, value.y);
  fp2_store(base + 32u, value.z);
}
