// Code generated by gnark DO NOT EDIT

// curvegpu:section fr_types begin
struct Fr {
  limbs: array<u32, 8>,
}
// curvegpu:section fr_types end

struct Params {
  count: u32,
  opcode: u32,
  _pad0: u32,
  _pad1: u32,
}

const FR_OP_COPY: u32 = 0u;
const FR_OP_ZERO: u32 = 1u;
const FR_OP_ONE: u32 = 2u;
const FR_OP_ADD: u32 = 3u;
const FR_OP_SUB: u32 = 4u;
const FR_OP_NEG: u32 = 5u;
const FR_OP_DOUBLE: u32 = 6u;
const FR_OP_NORMALIZE: u32 = 7u;
const FR_OP_EQUAL: u32 = 8u;
const FR_OP_MUL: u32 = 9u;
const FR_OP_SQUARE: u32 = 10u;
const FR_OP_TO_MONT: u32 = 11u;
const FR_OP_FROM_MONT: u32 = 12u;

// curvegpu:section fr_constants begin
const FR_LIMB16_MASK: u32 = 0xffffu;
const FR_QINV_NEG_16: u32 = 0xffffu;

const FR_MODULUS32: array<u32, 8> = array<u32, 8>(
  0x00000001u,
  0xffffffffu,
  0xfffe5bfeu,
  0x53bda402u,
  0x09a1d805u,
  0x3339d808u,
  0x299d7d48u,
  0x73eda753u,
);

const FR_MODULUS16: array<u32, 16> = array<u32, 16>(
  0x0001u, 0x0000u,
  0xffffu, 0xffffu,
  0x5bfeu, 0xfffeu,
  0xa402u, 0x53bdu,
  0xd805u, 0x09a1u,
  0xd808u, 0x3339u,
  0x7d48u, 0x299du,
  0xa753u, 0x73edu,
);
// curvegpu:section fr_constants end

@group(0) @binding(0) var<storage, read> input_a: array<u32>;
@group(0) @binding(1) var<storage, read> input_b: array<u32>;
@group(0) @binding(2) var<storage, read_write> output: array<u32>;
@group(0) @binding(3) var<uniform> params: Params;

// curvegpu:section fr_core begin
fn fr_zero() -> Fr {
  var z: Fr;
  z.limbs[0] = 0u;
  z.limbs[1] = 0u;
  z.limbs[2] = 0u;
  z.limbs[3] = 0u;
  z.limbs[4] = 0u;
  z.limbs[5] = 0u;
  z.limbs[6] = 0u;
  z.limbs[7] = 0u;
  return z;
}

fn fr_one() -> Fr {
  var z: Fr;
  z.limbs[0] = 0xfffffffeu;
  z.limbs[1] = 0x00000001u;
  z.limbs[2] = 0x00034802u;
  z.limbs[3] = 0x5884b7fau;
  z.limbs[4] = 0xecbc4ff5u;
  z.limbs[5] = 0x998c4fefu;
  z.limbs[6] = 0xacc5056fu;
  z.limbs[7] = 0x1824b159u;
  return z;
}

fn fr_one_regular() -> Fr {
  var z = fr_zero();
  z.limbs[0] = 1u;
  return z;
}

fn fr_rsquare_regular() -> Fr {
  var z: Fr;
  z.limbs[0] = 0xf3f29c6du;
  z.limbs[1] = 0xc999e990u;
  z.limbs[2] = 0x87925c23u;
  z.limbs[3] = 0x2b6cedcbu;
  z.limbs[4] = 0x7254398fu;
  z.limbs[5] = 0x05d31496u;
  z.limbs[6] = 0x9f59ff11u;
  z.limbs[7] = 0x0748d9d9u;
  return z;
}

fn fr_predicate(value: bool) -> Fr {
  let one = fr_one();
  var z: Fr;
  z.limbs[0] = select(0u, one.limbs[0], value);
  z.limbs[1] = select(0u, one.limbs[1], value);
  z.limbs[2] = select(0u, one.limbs[2], value);
  z.limbs[3] = select(0u, one.limbs[3], value);
  z.limbs[4] = select(0u, one.limbs[4], value);
  z.limbs[5] = select(0u, one.limbs[5], value);
  z.limbs[6] = select(0u, one.limbs[6], value);
  z.limbs[7] = select(0u, one.limbs[7], value);
  return z;
}

fn adc(a: u32, b: u32, carry: u32) -> vec2<u32> {
  let sum0 = a + b;
  let sum1 = sum0 + carry;
  return vec2<u32>(sum1, u32(sum0 < a) | u32(sum1 < sum0));
}

fn sbb(a: u32, b: u32, borrow: u32) -> vec2<u32> {
  let diff0 = a - b;
  let diff1 = diff0 - borrow;
  return vec2<u32>(diff1, u32(a < b) | u32(diff1 > diff0));
}

fn fr_is_zero(x: Fr) -> bool {
  return (x.limbs[0] | x.limbs[1] | x.limbs[2] | x.limbs[3] |
    x.limbs[4] | x.limbs[5] | x.limbs[6] | x.limbs[7]) == 0u;
}

fn fr_equal(x: Fr, y: Fr) -> bool {
  return (x.limbs[0] == y.limbs[0]) &&
    (x.limbs[1] == y.limbs[1]) &&
    (x.limbs[2] == y.limbs[2]) &&
    (x.limbs[3] == y.limbs[3]) &&
    (x.limbs[4] == y.limbs[4]) &&
    (x.limbs[5] == y.limbs[5]) &&
    (x.limbs[6] == y.limbs[6]) &&
    (x.limbs[7] == y.limbs[7]);
}

// x + y mod q: z = x + y, t = z - q; the result is t when the addition
// carried or the subtraction did not borrow (z >= q), else z.
fn fr_add(x: Fr, y: Fr) -> Fr {
  var z: Fr;
  var t: Fr;
  var lane = adc(x.limbs[0], y.limbs[0], 0u);
  z.limbs[0] = lane.x;
  lane = adc(x.limbs[1], y.limbs[1], lane.y);
  z.limbs[1] = lane.x;
  lane = adc(x.limbs[2], y.limbs[2], lane.y);
  z.limbs[2] = lane.x;
  lane = adc(x.limbs[3], y.limbs[3], lane.y);
  z.limbs[3] = lane.x;
  lane = adc(x.limbs[4], y.limbs[4], lane.y);
  z.limbs[4] = lane.x;
  lane = adc(x.limbs[5], y.limbs[5], lane.y);
  z.limbs[5] = lane.x;
  lane = adc(x.limbs[6], y.limbs[6], lane.y);
  z.limbs[6] = lane.x;
  lane = adc(x.limbs[7], y.limbs[7], lane.y);
  z.limbs[7] = lane.x;
  let carry = lane.y;
  lane = sbb(z.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(z.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(z.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(z.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(z.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(z.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(z.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(z.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  let use_t = (carry != 0u) || (lane.y == 0u);
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  return z;
}

// x - y mod q: z = x - y, t = z + q; the result is t when the subtraction
// borrowed, else z.
fn fr_sub(x: Fr, y: Fr) -> Fr {
  var z: Fr;
  var t: Fr;
  var lane = sbb(x.limbs[0], y.limbs[0], 0u);
  z.limbs[0] = lane.x;
  lane = sbb(x.limbs[1], y.limbs[1], lane.y);
  z.limbs[1] = lane.x;
  lane = sbb(x.limbs[2], y.limbs[2], lane.y);
  z.limbs[2] = lane.x;
  lane = sbb(x.limbs[3], y.limbs[3], lane.y);
  z.limbs[3] = lane.x;
  lane = sbb(x.limbs[4], y.limbs[4], lane.y);
  z.limbs[4] = lane.x;
  lane = sbb(x.limbs[5], y.limbs[5], lane.y);
  z.limbs[5] = lane.x;
  lane = sbb(x.limbs[6], y.limbs[6], lane.y);
  z.limbs[6] = lane.x;
  lane = sbb(x.limbs[7], y.limbs[7], lane.y);
  z.limbs[7] = lane.x;
  let use_t = lane.y != 0u;
  lane = adc(z.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = adc(z.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = adc(z.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = adc(z.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = adc(z.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = adc(z.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = adc(z.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = adc(z.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  return z;
}

// -x mod q: q - x, or zero when x is zero.
fn fr_neg(x: Fr) -> Fr {
  var t: Fr;
  var lane = sbb(FR_MODULUS32[0], x.limbs[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(FR_MODULUS32[1], x.limbs[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(FR_MODULUS32[2], x.limbs[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(FR_MODULUS32[3], x.limbs[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(FR_MODULUS32[4], x.limbs[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(FR_MODULUS32[5], x.limbs[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(FR_MODULUS32[6], x.limbs[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(FR_MODULUS32[7], x.limbs[7], lane.y);
  t.limbs[7] = lane.x;
  let nonzero = !fr_is_zero(x);
  var z: Fr;
  z.limbs[0] = select(0u, t.limbs[0], nonzero);
  z.limbs[1] = select(0u, t.limbs[1], nonzero);
  z.limbs[2] = select(0u, t.limbs[2], nonzero);
  z.limbs[3] = select(0u, t.limbs[3], nonzero);
  z.limbs[4] = select(0u, t.limbs[4], nonzero);
  z.limbs[5] = select(0u, t.limbs[5], nonzero);
  z.limbs[6] = select(0u, t.limbs[6], nonzero);
  z.limbs[7] = select(0u, t.limbs[7], nonzero);
  return z;
}

// 2x mod q: a left shift by one bit, then the same conditional subtraction
// as fr_add.
fn fr_double(x: Fr) -> Fr {
  var z: Fr;
  var t: Fr;
  z.limbs[0] = x.limbs[0] << 1u;
  z.limbs[1] = (x.limbs[1] << 1u) | (x.limbs[0] >> 31u);
  z.limbs[2] = (x.limbs[2] << 1u) | (x.limbs[1] >> 31u);
  z.limbs[3] = (x.limbs[3] << 1u) | (x.limbs[2] >> 31u);
  z.limbs[4] = (x.limbs[4] << 1u) | (x.limbs[3] >> 31u);
  z.limbs[5] = (x.limbs[5] << 1u) | (x.limbs[4] >> 31u);
  z.limbs[6] = (x.limbs[6] << 1u) | (x.limbs[5] >> 31u);
  z.limbs[7] = (x.limbs[7] << 1u) | (x.limbs[6] >> 31u);
  let carry = x.limbs[7] >> 31u;
  var lane: vec2<u32>;
  lane = sbb(z.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(z.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(z.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(z.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(z.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(z.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(z.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(z.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  let use_t = (carry != 0u) || (lane.y == 0u);
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  return z;
}

// Reduce a value in [0, 2q) to [0, q).
fn fr_normalize(x: Fr) -> Fr {
  var t: Fr;
  var z: Fr;
  var lane: vec2<u32>;
  lane = sbb(x.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(x.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(x.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(x.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(x.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(x.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(x.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(x.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  let use_t = lane.y == 0u;
  z.limbs[0] = select(x.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(x.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(x.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(x.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(x.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(x.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(x.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(x.limbs[7], t.limbs[7], use_t);
  return z;
}

// Montgomery multiplication (CIOS) over 16-bit digits: R = 2^(16*16).
// Each 16x16 partial product plus carries fits in a u32 without overflow.
// The digit loops are unrolled so the accumulator lives in registers; the
// final conditional subtraction is branch-free.
fn fr_mul(x: Fr, y: Fr) -> Fr {
  let a0 = x.limbs[0] & FR_LIMB16_MASK;
  let a1 = x.limbs[0] >> 16u;
  let a2 = x.limbs[1] & FR_LIMB16_MASK;
  let a3 = x.limbs[1] >> 16u;
  let a4 = x.limbs[2] & FR_LIMB16_MASK;
  let a5 = x.limbs[2] >> 16u;
  let a6 = x.limbs[3] & FR_LIMB16_MASK;
  let a7 = x.limbs[3] >> 16u;
  let a8 = x.limbs[4] & FR_LIMB16_MASK;
  let a9 = x.limbs[4] >> 16u;
  let a10 = x.limbs[5] & FR_LIMB16_MASK;
  let a11 = x.limbs[5] >> 16u;
  let a12 = x.limbs[6] & FR_LIMB16_MASK;
  let a13 = x.limbs[6] >> 16u;
  let a14 = x.limbs[7] & FR_LIMB16_MASK;
  let a15 = x.limbs[7] >> 16u;
  var t0 = 0u;
  var t1 = 0u;
  var t2 = 0u;
  var t3 = 0u;
  var t4 = 0u;
  var t5 = 0u;
  var t6 = 0u;
  var t7 = 0u;
  var t8 = 0u;
  var t9 = 0u;
  var t10 = 0u;
  var t11 = 0u;
  var t12 = 0u;
  var t13 = 0u;
  var t14 = 0u;
  var t15 = 0u;
  var t16 = 0u;
  var uv = 0u;
  var c = 0u;
  var m = 0u;
  for (var i = 0u; i < 8u; i = i + 1u) {
    let w = y.limbs[i];
    let b_lo = w & FR_LIMB16_MASK;
    let b_hi = w >> 16u;
    uv = t0 + a0 * b_lo;
    t0 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t1 + a1 * b_lo + c;
    t1 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + a2 * b_lo + c;
    t2 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + a3 * b_lo + c;
    t3 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + a4 * b_lo + c;
    t4 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + a5 * b_lo + c;
    t5 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + a6 * b_lo + c;
    t6 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + a7 * b_lo + c;
    t7 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + a8 * b_lo + c;
    t8 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + a9 * b_lo + c;
    t9 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + a10 * b_lo + c;
    t10 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + a11 * b_lo + c;
    t11 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + a12 * b_lo + c;
    t12 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + a13 * b_lo + c;
    t13 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + a14 * b_lo + c;
    t14 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + a15 * b_lo + c;
    t15 = uv & FR_LIMB16_MASK;
    t16 = uv >> 16u;
    m = (t0 * FR_QINV_NEG_16) & FR_LIMB16_MASK;
    // (t0 + m*q0) is 0 mod 2^16 by construction: only its carry survives.
    c = (t0 + m * FR_MODULUS16[0]) >> 16u;
    uv = t1 + m * FR_MODULUS16[1] + c;
    t0 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + m * FR_MODULUS16[2] + c;
    t1 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + m * FR_MODULUS16[3] + c;
    t2 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + m * FR_MODULUS16[4] + c;
    t3 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + m * FR_MODULUS16[5] + c;
    t4 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + m * FR_MODULUS16[6] + c;
    t5 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + m * FR_MODULUS16[7] + c;
    t6 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + m * FR_MODULUS16[8] + c;
    t7 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + m * FR_MODULUS16[9] + c;
    t8 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + m * FR_MODULUS16[10] + c;
    t9 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + m * FR_MODULUS16[11] + c;
    t10 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + m * FR_MODULUS16[12] + c;
    t11 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + m * FR_MODULUS16[13] + c;
    t12 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + m * FR_MODULUS16[14] + c;
    t13 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + m * FR_MODULUS16[15] + c;
    t14 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t16 + c;
    t15 = uv & FR_LIMB16_MASK;
    t16 = uv >> 16u;
    uv = t0 + a0 * b_hi;
    t0 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t1 + a1 * b_hi + c;
    t1 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + a2 * b_hi + c;
    t2 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + a3 * b_hi + c;
    t3 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + a4 * b_hi + c;
    t4 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + a5 * b_hi + c;
    t5 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + a6 * b_hi + c;
    t6 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + a7 * b_hi + c;
    t7 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + a8 * b_hi + c;
    t8 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + a9 * b_hi + c;
    t9 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + a10 * b_hi + c;
    t10 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + a11 * b_hi + c;
    t11 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + a12 * b_hi + c;
    t12 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + a13 * b_hi + c;
    t13 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + a14 * b_hi + c;
    t14 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + a15 * b_hi + c;
    t15 = uv & FR_LIMB16_MASK;
    t16 = uv >> 16u;
    m = (t0 * FR_QINV_NEG_16) & FR_LIMB16_MASK;
    // (t0 + m*q0) is 0 mod 2^16 by construction: only its carry survives.
    c = (t0 + m * FR_MODULUS16[0]) >> 16u;
    uv = t1 + m * FR_MODULUS16[1] + c;
    t0 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + m * FR_MODULUS16[2] + c;
    t1 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + m * FR_MODULUS16[3] + c;
    t2 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + m * FR_MODULUS16[4] + c;
    t3 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + m * FR_MODULUS16[5] + c;
    t4 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + m * FR_MODULUS16[6] + c;
    t5 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + m * FR_MODULUS16[7] + c;
    t6 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + m * FR_MODULUS16[8] + c;
    t7 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + m * FR_MODULUS16[9] + c;
    t8 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + m * FR_MODULUS16[10] + c;
    t9 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + m * FR_MODULUS16[11] + c;
    t10 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + m * FR_MODULUS16[12] + c;
    t11 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + m * FR_MODULUS16[13] + c;
    t12 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + m * FR_MODULUS16[14] + c;
    t13 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + m * FR_MODULUS16[15] + c;
    t14 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t16 + c;
    t15 = uv & FR_LIMB16_MASK;
    t16 = uv >> 16u;
  }

  var z: Fr;
  z.limbs[0] = t0 | (t1 << 16u);
  z.limbs[1] = t2 | (t3 << 16u);
  z.limbs[2] = t4 | (t5 << 16u);
  z.limbs[3] = t6 | (t7 << 16u);
  z.limbs[4] = t8 | (t9 << 16u);
  z.limbs[5] = t10 | (t11 << 16u);
  z.limbs[6] = t12 | (t13 << 16u);
  z.limbs[7] = t14 | (t15 << 16u);
  var t: Fr;
  var lane: vec2<u32>;
  lane = sbb(z.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(z.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(z.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(z.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(z.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(z.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(z.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(z.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  let use_t = (t16 != 0u) || (lane.y == 0u);
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  return z;
}

fn fr_square(x: Fr) -> Fr {
  return fr_mul(x, x);
}
// curvegpu:section fr_core end

fn fr_dispatch(opcode: u32, a: Fr, b: Fr) -> Fr {
  if (opcode == FR_OP_COPY) {
    return a;
  }
  if (opcode == FR_OP_ZERO) {
    return fr_zero();
  }
  if (opcode == FR_OP_ONE) {
    return fr_one();
  }
  if (opcode == FR_OP_ADD) {
    return fr_add(a, b);
  }
  if (opcode == FR_OP_SUB) {
    return fr_sub(a, b);
  }
  if (opcode == FR_OP_NEG) {
    return fr_neg(a);
  }
  if (opcode == FR_OP_DOUBLE) {
    return fr_double(a);
  }
  if (opcode == FR_OP_NORMALIZE) {
    return fr_normalize(a);
  }
  if (opcode == FR_OP_EQUAL) {
    return fr_predicate(fr_equal(a, b));
  }
  if (opcode == FR_OP_MUL) {
    return fr_mul(a, b);
  }
  if (opcode == FR_OP_SQUARE) {
    return fr_square(a);
  }
  if (opcode == FR_OP_TO_MONT) {
    return fr_mul(a, fr_rsquare_regular());
  }
  if (opcode == FR_OP_FROM_MONT) {
    return fr_mul(a, fr_one_regular());
  }
  return fr_zero();
}

fn fr_load_a(index: u32) -> Fr {
  let base = index * 8u;
  var z: Fr;
  z.limbs[0] = input_a[base + 0u];
  z.limbs[1] = input_a[base + 1u];
  z.limbs[2] = input_a[base + 2u];
  z.limbs[3] = input_a[base + 3u];
  z.limbs[4] = input_a[base + 4u];
  z.limbs[5] = input_a[base + 5u];
  z.limbs[6] = input_a[base + 6u];
  z.limbs[7] = input_a[base + 7u];
  return z;
}

fn fr_load_b(index: u32) -> Fr {
  let base = index * 8u;
  var z: Fr;
  z.limbs[0] = input_b[base + 0u];
  z.limbs[1] = input_b[base + 1u];
  z.limbs[2] = input_b[base + 2u];
  z.limbs[3] = input_b[base + 3u];
  z.limbs[4] = input_b[base + 4u];
  z.limbs[5] = input_b[base + 5u];
  z.limbs[6] = input_b[base + 6u];
  z.limbs[7] = input_b[base + 7u];
  return z;
}

fn fr_store(index: u32, value: Fr) {
  let base = index * 8u;
  output[base + 0u] = value.limbs[0];
  output[base + 1u] = value.limbs[1];
  output[base + 2u] = value.limbs[2];
  output[base + 3u] = value.limbs[3];
  output[base + 4u] = value.limbs[4];
  output[base + 5u] = value.limbs[5];
  output[base + 6u] = value.limbs[6];
  output[base + 7u] = value.limbs[7];
}

override WORKGROUP_SIZE: u32 = 64;

@compute @workgroup_size(WORKGROUP_SIZE)
fn fr_ops_main(@builtin(global_invocation_id) id: vec3<u32>) {
  let i = id.x;
  if (i >= params.count) {
    return;
  }
  fr_store(i, fr_dispatch(params.opcode, fr_load_a(i), fr_load_b(i)));
}
