// Code generated by gnark DO NOT EDIT

// curvegpu:section fp-types begin
struct Fp {
  limbs: array<u32, 12>,
}
// curvegpu:section fp-types end

struct Params {
  count: u32,
  opcode: u32,
  _pad0: u32,
  _pad1: u32,
}

const FP_OP_COPY: u32 = 0u;
const FP_OP_ZERO: u32 = 1u;
const FP_OP_ONE: u32 = 2u;
const FP_OP_ADD: u32 = 3u;
const FP_OP_SUB: u32 = 4u;
const FP_OP_NEG: u32 = 5u;
const FP_OP_DOUBLE: u32 = 6u;
const FP_OP_NORMALIZE: u32 = 7u;
const FP_OP_EQUAL: u32 = 8u;
const FP_OP_MUL: u32 = 9u;
const FP_OP_SQUARE: u32 = 10u;
const FP_OP_TO_MONT: u32 = 11u;
const FP_OP_FROM_MONT: u32 = 12u;

// curvegpu:section fp-consts begin
const FP_LIMB16_MASK: u32 = 0xffffu;
const FP_QINV_NEG_16: u32 = 0xffffu;

const FP_MODULUS32: array<u32, 12> = array<u32, 12>(
  0x00000001u,
  0x8508c000u,
  0x30000000u,
  0x170b5d44u,
  0xba094800u,
  0x1ef3622fu,
  0x00f5138fu,
  0x1a22d9f3u,
  0x6ca1493bu,
  0xc63b05c0u,
  0x17c510eau,
  0x01ae3a46u,
);

const FP_MODULUS16: array<u32, 24> = array<u32, 24>(
  0x0001u, 0x0000u,
  0xc000u, 0x8508u,
  0x0000u, 0x3000u,
  0x5d44u, 0x170bu,
  0x4800u, 0xba09u,
  0x622fu, 0x1ef3u,
  0x138fu, 0x00f5u,
  0xd9f3u, 0x1a22u,
  0x493bu, 0x6ca1u,
  0x05c0u, 0xc63bu,
  0x10eau, 0x17c5u,
  0x3a46u, 0x01aeu,
);

const FP_MODULUS_MINUS_TWO: array<u32, 12> = array<u32, 12>(
  0xffffffffu,
  0x8508bfffu,
  0x30000000u,
  0x170b5d44u,
  0xba094800u,
  0x1ef3622fu,
  0x00f5138fu,
  0x1a22d9f3u,
  0x6ca1493bu,
  0xc63b05c0u,
  0x17c510eau,
  0x01ae3a46u,
);
// curvegpu:section fp-consts end

@group(0) @binding(0) var<storage, read> input_a: array<u32>;
@group(0) @binding(1) var<storage, read> input_b: array<u32>;
@group(0) @binding(2) var<storage, read_write> output: array<u32>;
@group(0) @binding(3) var<uniform> params: Params;

// curvegpu:section fp-core begin
fn fp_zero() -> Fp {
  var z: Fp;
  z.limbs[0] = 0u;
  z.limbs[1] = 0u;
  z.limbs[2] = 0u;
  z.limbs[3] = 0u;
  z.limbs[4] = 0u;
  z.limbs[5] = 0u;
  z.limbs[6] = 0u;
  z.limbs[7] = 0u;
  z.limbs[8] = 0u;
  z.limbs[9] = 0u;
  z.limbs[10] = 0u;
  z.limbs[11] = 0u;
  return z;
}

fn fp_one() -> Fp {
  var z: Fp;
  z.limbs[0] = 0xffffff68u;
  z.limbs[1] = 0x02cdffffu;
  z.limbs[2] = 0x7fffffb1u;
  z.limbs[3] = 0x51409f83u;
  z.limbs[4] = 0x8a7d3ff2u;
  z.limbs[5] = 0x9f7db3a9u;
  z.limbs[6] = 0x6e7c6305u;
  z.limbs[7] = 0x7b4e97b7u;
  z.limbs[8] = 0x803c84e8u;
  z.limbs[9] = 0x4cf495bfu;
  z.limbs[10] = 0xe2fdf49au;
  z.limbs[11] = 0x008d6661u;
  return z;
}

fn fp_one_regular() -> Fp {
  var z = fp_zero();
  z.limbs[0] = 1u;
  return z;
}

fn fp_rsquare_regular() -> Fp {
  var z: Fp;
  z.limbs[0] = 0x9400cd22u;
  z.limbs[1] = 0xb786686cu;
  z.limbs[2] = 0xb00431b1u;
  z.limbs[3] = 0x0329fcaau;
  z.limbs[4] = 0x62d6b46du;
  z.limbs[5] = 0x22a5f111u;
  z.limbs[6] = 0x827dc3acu;
  z.limbs[7] = 0xbfdf7d03u;
  z.limbs[8] = 0x41790bf9u;
  z.limbs[9] = 0x837e92f0u;
  z.limbs[10] = 0x1e914b88u;
  z.limbs[11] = 0x006dfccbu;
  return z;
}

fn fp_predicate(value: bool) -> Fp {
  let one = fp_one();
  var z: Fp;
  z.limbs[0] = select(0u, one.limbs[0], value);
  z.limbs[1] = select(0u, one.limbs[1], value);
  z.limbs[2] = select(0u, one.limbs[2], value);
  z.limbs[3] = select(0u, one.limbs[3], value);
  z.limbs[4] = select(0u, one.limbs[4], value);
  z.limbs[5] = select(0u, one.limbs[5], value);
  z.limbs[6] = select(0u, one.limbs[6], value);
  z.limbs[7] = select(0u, one.limbs[7], value);
  z.limbs[8] = select(0u, one.limbs[8], value);
  z.limbs[9] = select(0u, one.limbs[9], value);
  z.limbs[10] = select(0u, one.limbs[10], value);
  z.limbs[11] = select(0u, one.limbs[11], value);
  return z;
}

fn adc(a: u32, b: u32, carry: u32) -> vec2<u32> {
  let sum0 = a + b;
  let sum1 = sum0 + carry;
  return vec2<u32>(sum1, u32(sum0 < a) | u32(sum1 < sum0));
}

fn sbb(a: u32, b: u32, borrow: u32) -> vec2<u32> {
  let diff0 = a - b;
  let diff1 = diff0 - borrow;
  return vec2<u32>(diff1, u32(a < b) | u32(diff1 > diff0));
}

fn fp_is_zero(x: Fp) -> bool {
  return (x.limbs[0] | x.limbs[1] | x.limbs[2] | x.limbs[3] |
    x.limbs[4] | x.limbs[5] | x.limbs[6] | x.limbs[7] |
    x.limbs[8] | x.limbs[9] | x.limbs[10] | x.limbs[11]) == 0u;
}

fn fp_equal(x: Fp, y: Fp) -> bool {
  return (x.limbs[0] == y.limbs[0]) &&
    (x.limbs[1] == y.limbs[1]) &&
    (x.limbs[2] == y.limbs[2]) &&
    (x.limbs[3] == y.limbs[3]) &&
    (x.limbs[4] == y.limbs[4]) &&
    (x.limbs[5] == y.limbs[5]) &&
    (x.limbs[6] == y.limbs[6]) &&
    (x.limbs[7] == y.limbs[7]) &&
    (x.limbs[8] == y.limbs[8]) &&
    (x.limbs[9] == y.limbs[9]) &&
    (x.limbs[10] == y.limbs[10]) &&
    (x.limbs[11] == y.limbs[11]);
}

// x + y mod q: z = x + y, t = z - q; the result is t when the addition
// carried or the subtraction did not borrow (z >= q), else z.
fn fp_add(x: Fp, y: Fp) -> Fp {
  var z: Fp;
  var t: Fp;
  var lane = adc(x.limbs[0], y.limbs[0], 0u);
  z.limbs[0] = lane.x;
  lane = adc(x.limbs[1], y.limbs[1], lane.y);
  z.limbs[1] = lane.x;
  lane = adc(x.limbs[2], y.limbs[2], lane.y);
  z.limbs[2] = lane.x;
  lane = adc(x.limbs[3], y.limbs[3], lane.y);
  z.limbs[3] = lane.x;
  lane = adc(x.limbs[4], y.limbs[4], lane.y);
  z.limbs[4] = lane.x;
  lane = adc(x.limbs[5], y.limbs[5], lane.y);
  z.limbs[5] = lane.x;
  lane = adc(x.limbs[6], y.limbs[6], lane.y);
  z.limbs[6] = lane.x;
  lane = adc(x.limbs[7], y.limbs[7], lane.y);
  z.limbs[7] = lane.x;
  lane = adc(x.limbs[8], y.limbs[8], lane.y);
  z.limbs[8] = lane.x;
  lane = adc(x.limbs[9], y.limbs[9], lane.y);
  z.limbs[9] = lane.x;
  lane = adc(x.limbs[10], y.limbs[10], lane.y);
  z.limbs[10] = lane.x;
  lane = adc(x.limbs[11], y.limbs[11], lane.y);
  z.limbs[11] = lane.x;
  let carry = lane.y;
  lane = sbb(z.limbs[0], FP_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(z.limbs[1], FP_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(z.limbs[2], FP_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(z.limbs[3], FP_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(z.limbs[4], FP_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(z.limbs[5], FP_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(z.limbs[6], FP_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(z.limbs[7], FP_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  lane = sbb(z.limbs[8], FP_MODULUS32[8], lane.y);
  t.limbs[8] = lane.x;
  lane = sbb(z.limbs[9], FP_MODULUS32[9], lane.y);
  t.limbs[9] = lane.x;
  lane = sbb(z.limbs[10], FP_MODULUS32[10], lane.y);
  t.limbs[10] = lane.x;
  lane = sbb(z.limbs[11], FP_MODULUS32[11], lane.y);
  t.limbs[11] = lane.x;
  let use_t = (carry != 0u) || (lane.y == 0u);
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  z.limbs[8] = select(z.limbs[8], t.limbs[8], use_t);
  z.limbs[9] = select(z.limbs[9], t.limbs[9], use_t);
  z.limbs[10] = select(z.limbs[10], t.limbs[10], use_t);
  z.limbs[11] = select(z.limbs[11], t.limbs[11], use_t);
  return z;
}

// x - y mod q: z = x - y, t = z + q; the result is t when the subtraction
// borrowed, else z.
fn fp_sub(x: Fp, y: Fp) -> Fp {
  var z: Fp;
  var t: Fp;
  var lane = sbb(x.limbs[0], y.limbs[0], 0u);
  z.limbs[0] = lane.x;
  lane = sbb(x.limbs[1], y.limbs[1], lane.y);
  z.limbs[1] = lane.x;
  lane = sbb(x.limbs[2], y.limbs[2], lane.y);
  z.limbs[2] = lane.x;
  lane = sbb(x.limbs[3], y.limbs[3], lane.y);
  z.limbs[3] = lane.x;
  lane = sbb(x.limbs[4], y.limbs[4], lane.y);
  z.limbs[4] = lane.x;
  lane = sbb(x.limbs[5], y.limbs[5], lane.y);
  z.limbs[5] = lane.x;
  lane = sbb(x.limbs[6], y.limbs[6], lane.y);
  z.limbs[6] = lane.x;
  lane = sbb(x.limbs[7], y.limbs[7], lane.y);
  z.limbs[7] = lane.x;
  lane = sbb(x.limbs[8], y.limbs[8], lane.y);
  z.limbs[8] = lane.x;
  lane = sbb(x.limbs[9], y.limbs[9], lane.y);
  z.limbs[9] = lane.x;
  lane = sbb(x.limbs[10], y.limbs[10], lane.y);
  z.limbs[10] = lane.x;
  lane = sbb(x.limbs[11], y.limbs[11], lane.y);
  z.limbs[11] = lane.x;
  let use_t = lane.y != 0u;
  lane = adc(z.limbs[0], FP_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = adc(z.limbs[1], FP_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = adc(z.limbs[2], FP_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = adc(z.limbs[3], FP_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = adc(z.limbs[4], FP_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = adc(z.limbs[5], FP_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = adc(z.limbs[6], FP_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = adc(z.limbs[7], FP_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  lane = adc(z.limbs[8], FP_MODULUS32[8], lane.y);
  t.limbs[8] = lane.x;
  lane = adc(z.limbs[9], FP_MODULUS32[9], lane.y);
  t.limbs[9] = lane.x;
  lane = adc(z.limbs[10], FP_MODULUS32[10], lane.y);
  t.limbs[10] = lane.x;
  lane = adc(z.limbs[11], FP_MODULUS32[11], lane.y);
  t.limbs[11] = lane.x;
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  z.limbs[8] = select(z.limbs[8], t.limbs[8], use_t);
  z.limbs[9] = select(z.limbs[9], t.limbs[9], use_t);
  z.limbs[10] = select(z.limbs[10], t.limbs[10], use_t);
  z.limbs[11] = select(z.limbs[11], t.limbs[11], use_t);
  return z;
}

// -x mod q: q - x, or zero when x is zero.
fn fp_neg(x: Fp) -> Fp {
  var t: Fp;
  var lane = sbb(FP_MODULUS32[0], x.limbs[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(FP_MODULUS32[1], x.limbs[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(FP_MODULUS32[2], x.limbs[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(FP_MODULUS32[3], x.limbs[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(FP_MODULUS32[4], x.limbs[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(FP_MODULUS32[5], x.limbs[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(FP_MODULUS32[6], x.limbs[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(FP_MODULUS32[7], x.limbs[7], lane.y);
  t.limbs[7] = lane.x;
  lane = sbb(FP_MODULUS32[8], x.limbs[8], lane.y);
  t.limbs[8] = lane.x;
  lane = sbb(FP_MODULUS32[9], x.limbs[9], lane.y);
  t.limbs[9] = lane.x;
  lane = sbb(FP_MODULUS32[10], x.limbs[10], lane.y);
  t.limbs[10] = lane.x;
  lane = sbb(FP_MODULUS32[11], x.limbs[11], lane.y);
  t.limbs[11] = lane.x;
  let nonzero = !fp_is_zero(x);
  var z: Fp;
  z.limbs[0] = select(0u, t.limbs[0], nonzero);
  z.limbs[1] = select(0u, t.limbs[1], nonzero);
  z.limbs[2] = select(0u, t.limbs[2], nonzero);
  z.limbs[3] = select(0u, t.limbs[3], nonzero);
  z.limbs[4] = select(0u, t.limbs[4], nonzero);
  z.limbs[5] = select(0u, t.limbs[5], nonzero);
  z.limbs[6] = select(0u, t.limbs[6], nonzero);
  z.limbs[7] = select(0u, t.limbs[7], nonzero);
  z.limbs[8] = select(0u, t.limbs[8], nonzero);
  z.limbs[9] = select(0u, t.limbs[9], nonzero);
  z.limbs[10] = select(0u, t.limbs[10], nonzero);
  z.limbs[11] = select(0u, t.limbs[11], nonzero);
  return z;
}

// 2x mod q: a left shift by one bit, then the same conditional subtraction
// as fp_add.
fn fp_double(x: Fp) -> Fp {
  var z: Fp;
  var t: Fp;
  z.limbs[0] = x.limbs[0] << 1u;
  z.limbs[1] = (x.limbs[1] << 1u) | (x.limbs[0] >> 31u);
  z.limbs[2] = (x.limbs[2] << 1u) | (x.limbs[1] >> 31u);
  z.limbs[3] = (x.limbs[3] << 1u) | (x.limbs[2] >> 31u);
  z.limbs[4] = (x.limbs[4] << 1u) | (x.limbs[3] >> 31u);
  z.limbs[5] = (x.limbs[5] << 1u) | (x.limbs[4] >> 31u);
  z.limbs[6] = (x.limbs[6] << 1u) | (x.limbs[5] >> 31u);
  z.limbs[7] = (x.limbs[7] << 1u) | (x.limbs[6] >> 31u);
  z.limbs[8] = (x.limbs[8] << 1u) | (x.limbs[7] >> 31u);
  z.limbs[9] = (x.limbs[9] << 1u) | (x.limbs[8] >> 31u);
  z.limbs[10] = (x.limbs[10] << 1u) | (x.limbs[9] >> 31u);
  z.limbs[11] = (x.limbs[11] << 1u) | (x.limbs[10] >> 31u);
  let carry = x.limbs[11] >> 31u;
  var lane: vec2<u32>;
  lane = sbb(z.limbs[0], FP_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(z.limbs[1], FP_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(z.limbs[2], FP_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(z.limbs[3], FP_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(z.limbs[4], FP_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(z.limbs[5], FP_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(z.limbs[6], FP_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(z.limbs[7], FP_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  lane = sbb(z.limbs[8], FP_MODULUS32[8], lane.y);
  t.limbs[8] = lane.x;
  lane = sbb(z.limbs[9], FP_MODULUS32[9], lane.y);
  t.limbs[9] = lane.x;
  lane = sbb(z.limbs[10], FP_MODULUS32[10], lane.y);
  t.limbs[10] = lane.x;
  lane = sbb(z.limbs[11], FP_MODULUS32[11], lane.y);
  t.limbs[11] = lane.x;
  let use_t = (carry != 0u) || (lane.y == 0u);
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  z.limbs[8] = select(z.limbs[8], t.limbs[8], use_t);
  z.limbs[9] = select(z.limbs[9], t.limbs[9], use_t);
  z.limbs[10] = select(z.limbs[10], t.limbs[10], use_t);
  z.limbs[11] = select(z.limbs[11], t.limbs[11], use_t);
  return z;
}

// Reduce a value in [0, 2q) to [0, q).
fn fp_normalize(x: Fp) -> Fp {
  var t: Fp;
  var z: Fp;
  var lane: vec2<u32>;
  lane = sbb(x.limbs[0], FP_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(x.limbs[1], FP_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(x.limbs[2], FP_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(x.limbs[3], FP_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(x.limbs[4], FP_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(x.limbs[5], FP_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(x.limbs[6], FP_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(x.limbs[7], FP_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  lane = sbb(x.limbs[8], FP_MODULUS32[8], lane.y);
  t.limbs[8] = lane.x;
  lane = sbb(x.limbs[9], FP_MODULUS32[9], lane.y);
  t.limbs[9] = lane.x;
  lane = sbb(x.limbs[10], FP_MODULUS32[10], lane.y);
  t.limbs[10] = lane.x;
  lane = sbb(x.limbs[11], FP_MODULUS32[11], lane.y);
  t.limbs[11] = lane.x;
  let use_t = lane.y == 0u;
  z.limbs[0] = select(x.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(x.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(x.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(x.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(x.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(x.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(x.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(x.limbs[7], t.limbs[7], use_t);
  z.limbs[8] = select(x.limbs[8], t.limbs[8], use_t);
  z.limbs[9] = select(x.limbs[9], t.limbs[9], use_t);
  z.limbs[10] = select(x.limbs[10], t.limbs[10], use_t);
  z.limbs[11] = select(x.limbs[11], t.limbs[11], use_t);
  return z;
}

// Montgomery multiplication (CIOS) over 16-bit digits: R = 2^(16*24).
// Each 16x16 partial product plus carries fits in a u32 without overflow.
// The digit loops are unrolled so the accumulator lives in registers; the
// final conditional subtraction is branch-free.
fn fp_mul(x: Fp, y: Fp) -> Fp {
  let a0 = x.limbs[0] & FP_LIMB16_MASK;
  let a1 = x.limbs[0] >> 16u;
  let a2 = x.limbs[1] & FP_LIMB16_MASK;
  let a3 = x.limbs[1] >> 16u;
  let a4 = x.limbs[2] & FP_LIMB16_MASK;
  let a5 = x.limbs[2] >> 16u;
  let a6 = x.limbs[3] & FP_LIMB16_MASK;
  let a7 = x.limbs[3] >> 16u;
  let a8 = x.limbs[4] & FP_LIMB16_MASK;
  let a9 = x.limbs[4] >> 16u;
  let a10 = x.limbs[5] & FP_LIMB16_MASK;
  let a11 = x.limbs[5] >> 16u;
  let a12 = x.limbs[6] & FP_LIMB16_MASK;
  let a13 = x.limbs[6] >> 16u;
  let a14 = x.limbs[7] & FP_LIMB16_MASK;
  let a15 = x.limbs[7] >> 16u;
  let a16 = x.limbs[8] & FP_LIMB16_MASK;
  let a17 = x.limbs[8] >> 16u;
  let a18 = x.limbs[9] & FP_LIMB16_MASK;
  let a19 = x.limbs[9] >> 16u;
  let a20 = x.limbs[10] & FP_LIMB16_MASK;
  let a21 = x.limbs[10] >> 16u;
  let a22 = x.limbs[11] & FP_LIMB16_MASK;
  let a23 = x.limbs[11] >> 16u;
  var t0 = 0u;
  var t1 = 0u;
  var t2 = 0u;
  var t3 = 0u;
  var t4 = 0u;
  var t5 = 0u;
  var t6 = 0u;
  var t7 = 0u;
  var t8 = 0u;
  var t9 = 0u;
  var t10 = 0u;
  var t11 = 0u;
  var t12 = 0u;
  var t13 = 0u;
  var t14 = 0u;
  var t15 = 0u;
  var t16 = 0u;
  var t17 = 0u;
  var t18 = 0u;
  var t19 = 0u;
  var t20 = 0u;
  var t21 = 0u;
  var t22 = 0u;
  var t23 = 0u;
  var t24 = 0u;
  var uv = 0u;
  var c = 0u;
  var m = 0u;
  for (var i = 0u; i < 12u; i = i + 1u) {
    let w = y.limbs[i];
    let b_lo = w & FP_LIMB16_MASK;
    let b_hi = w >> 16u;
    uv = t0 + a0 * b_lo;
    t0 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t1 + a1 * b_lo + c;
    t1 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + a2 * b_lo + c;
    t2 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + a3 * b_lo + c;
    t3 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + a4 * b_lo + c;
    t4 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + a5 * b_lo + c;
    t5 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + a6 * b_lo + c;
    t6 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + a7 * b_lo + c;
    t7 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + a8 * b_lo + c;
    t8 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + a9 * b_lo + c;
    t9 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + a10 * b_lo + c;
    t10 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + a11 * b_lo + c;
    t11 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + a12 * b_lo + c;
    t12 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + a13 * b_lo + c;
    t13 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + a14 * b_lo + c;
    t14 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + a15 * b_lo + c;
    t15 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t16 + a16 * b_lo + c;
    t16 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t17 + a17 * b_lo + c;
    t17 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t18 + a18 * b_lo + c;
    t18 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t19 + a19 * b_lo + c;
    t19 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t20 + a20 * b_lo + c;
    t20 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t21 + a21 * b_lo + c;
    t21 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t22 + a22 * b_lo + c;
    t22 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t23 + a23 * b_lo + c;
    t23 = uv & FP_LIMB16_MASK;
    t24 = uv >> 16u;
    m = (t0 * FP_QINV_NEG_16) & FP_LIMB16_MASK;
    // (t0 + m*q0) is 0 mod 2^16 by construction: only its carry survives.
    c = (t0 + m * FP_MODULUS16[0]) >> 16u;
    uv = t1 + m * FP_MODULUS16[1] + c;
    t0 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + m * FP_MODULUS16[2] + c;
    t1 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + m * FP_MODULUS16[3] + c;
    t2 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + m * FP_MODULUS16[4] + c;
    t3 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + m * FP_MODULUS16[5] + c;
    t4 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + m * FP_MODULUS16[6] + c;
    t5 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + m * FP_MODULUS16[7] + c;
    t6 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + m * FP_MODULUS16[8] + c;
    t7 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + m * FP_MODULUS16[9] + c;
    t8 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + m * FP_MODULUS16[10] + c;
    t9 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + m * FP_MODULUS16[11] + c;
    t10 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + m * FP_MODULUS16[12] + c;
    t11 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + m * FP_MODULUS16[13] + c;
    t12 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + m * FP_MODULUS16[14] + c;
    t13 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + m * FP_MODULUS16[15] + c;
    t14 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t16 + m * FP_MODULUS16[16] + c;
    t15 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t17 + m * FP_MODULUS16[17] + c;
    t16 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t18 + m * FP_MODULUS16[18] + c;
    t17 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t19 + m * FP_MODULUS16[19] + c;
    t18 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t20 + m * FP_MODULUS16[20] + c;
    t19 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t21 + m * FP_MODULUS16[21] + c;
    t20 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t22 + m * FP_MODULUS16[22] + c;
    t21 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t23 + m * FP_MODULUS16[23] + c;
    t22 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t24 + c;
    t23 = uv & FP_LIMB16_MASK;
    t24 = uv >> 16u;
    uv = t0 + a0 * b_hi;
    t0 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t1 + a1 * b_hi + c;
    t1 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + a2 * b_hi + c;
    t2 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + a3 * b_hi + c;
    t3 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + a4 * b_hi + c;
    t4 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + a5 * b_hi + c;
    t5 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + a6 * b_hi + c;
    t6 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + a7 * b_hi + c;
    t7 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + a8 * b_hi + c;
    t8 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + a9 * b_hi + c;
    t9 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + a10 * b_hi + c;
    t10 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + a11 * b_hi + c;
    t11 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + a12 * b_hi + c;
    t12 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + a13 * b_hi + c;
    t13 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + a14 * b_hi + c;
    t14 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + a15 * b_hi + c;
    t15 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t16 + a16 * b_hi + c;
    t16 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t17 + a17 * b_hi + c;
    t17 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t18 + a18 * b_hi + c;
    t18 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t19 + a19 * b_hi + c;
    t19 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t20 + a20 * b_hi + c;
    t20 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t21 + a21 * b_hi + c;
    t21 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t22 + a22 * b_hi + c;
    t22 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t23 + a23 * b_hi + c;
    t23 = uv & FP_LIMB16_MASK;
    t24 = uv >> 16u;
    m = (t0 * FP_QINV_NEG_16) & FP_LIMB16_MASK;
    // (t0 + m*q0) is 0 mod 2^16 by construction: only its carry survives.
    c = (t0 + m * FP_MODULUS16[0]) >> 16u;
    uv = t1 + m * FP_MODULUS16[1] + c;
    t0 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + m * FP_MODULUS16[2] + c;
    t1 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + m * FP_MODULUS16[3] + c;
    t2 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + m * FP_MODULUS16[4] + c;
    t3 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + m * FP_MODULUS16[5] + c;
    t4 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + m * FP_MODULUS16[6] + c;
    t5 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + m * FP_MODULUS16[7] + c;
    t6 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + m * FP_MODULUS16[8] + c;
    t7 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + m * FP_MODULUS16[9] + c;
    t8 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + m * FP_MODULUS16[10] + c;
    t9 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + m * FP_MODULUS16[11] + c;
    t10 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + m * FP_MODULUS16[12] + c;
    t11 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + m * FP_MODULUS16[13] + c;
    t12 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + m * FP_MODULUS16[14] + c;
    t13 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + m * FP_MODULUS16[15] + c;
    t14 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t16 + m * FP_MODULUS16[16] + c;
    t15 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t17 + m * FP_MODULUS16[17] + c;
    t16 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t18 + m * FP_MODULUS16[18] + c;
    t17 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t19 + m * FP_MODULUS16[19] + c;
    t18 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t20 + m * FP_MODULUS16[20] + c;
    t19 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t21 + m * FP_MODULUS16[21] + c;
    t20 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t22 + m * FP_MODULUS16[22] + c;
    t21 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t23 + m * FP_MODULUS16[23] + c;
    t22 = uv & FP_LIMB16_MASK;
    c = uv >> 16u;
    uv = t24 + c;
    t23 = uv & FP_LIMB16_MASK;
    t24 = uv >> 16u;
  }

  var z: Fp;
  z.limbs[0] = t0 | (t1 << 16u);
  z.limbs[1] = t2 | (t3 << 16u);
  z.limbs[2] = t4 | (t5 << 16u);
  z.limbs[3] = t6 | (t7 << 16u);
  z.limbs[4] = t8 | (t9 << 16u);
  z.limbs[5] = t10 | (t11 << 16u);
  z.limbs[6] = t12 | (t13 << 16u);
  z.limbs[7] = t14 | (t15 << 16u);
  z.limbs[8] = t16 | (t17 << 16u);
  z.limbs[9] = t18 | (t19 << 16u);
  z.limbs[10] = t20 | (t21 << 16u);
  z.limbs[11] = t22 | (t23 << 16u);
  var t: Fp;
  var lane: vec2<u32>;
  lane = sbb(z.limbs[0], FP_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(z.limbs[1], FP_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(z.limbs[2], FP_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(z.limbs[3], FP_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(z.limbs[4], FP_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(z.limbs[5], FP_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(z.limbs[6], FP_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(z.limbs[7], FP_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  lane = sbb(z.limbs[8], FP_MODULUS32[8], lane.y);
  t.limbs[8] = lane.x;
  lane = sbb(z.limbs[9], FP_MODULUS32[9], lane.y);
  t.limbs[9] = lane.x;
  lane = sbb(z.limbs[10], FP_MODULUS32[10], lane.y);
  t.limbs[10] = lane.x;
  lane = sbb(z.limbs[11], FP_MODULUS32[11], lane.y);
  t.limbs[11] = lane.x;
  let use_t = (t24 != 0u) || (lane.y == 0u);
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  z.limbs[8] = select(z.limbs[8], t.limbs[8], use_t);
  z.limbs[9] = select(z.limbs[9], t.limbs[9], use_t);
  z.limbs[10] = select(z.limbs[10], t.limbs[10], use_t);
  z.limbs[11] = select(z.limbs[11], t.limbs[11], use_t);
  return z;
}

fn fp_square(x: Fp) -> Fp {
  return fp_mul(x, x);
}

// Fermat inversion: x^(q-2). Returns zero for zero.
fn fp_inverse(x: Fp) -> Fp {
  if (fp_is_zero(x)) {
    return fp_zero();
  }
  var acc = fp_one();
  for (var word_index: i32 = 11; word_index >= 0; word_index = word_index - 1) {
    let word = FP_MODULUS_MINUS_TWO[u32(word_index)];
    for (var bit_index: i32 = 31; bit_index >= 0; bit_index = bit_index - 1) {
      acc = fp_square(acc);
      if (((word >> u32(bit_index)) & 1u) != 0u) {
        acc = fp_mul(acc, x);
      }
    }
  }
  return acc;
}
// curvegpu:section fp-core end

fn fp_dispatch(opcode: u32, a: Fp, b: Fp) -> Fp {
  if (opcode == FP_OP_COPY) {
    return a;
  }
  if (opcode == FP_OP_ZERO) {
    return fp_zero();
  }
  if (opcode == FP_OP_ONE) {
    return fp_one();
  }
  if (opcode == FP_OP_ADD) {
    return fp_add(a, b);
  }
  if (opcode == FP_OP_SUB) {
    return fp_sub(a, b);
  }
  if (opcode == FP_OP_NEG) {
    return fp_neg(a);
  }
  if (opcode == FP_OP_DOUBLE) {
    return fp_double(a);
  }
  if (opcode == FP_OP_NORMALIZE) {
    return fp_normalize(a);
  }
  if (opcode == FP_OP_EQUAL) {
    return fp_predicate(fp_equal(a, b));
  }
  if (opcode == FP_OP_MUL) {
    return fp_mul(a, b);
  }
  if (opcode == FP_OP_SQUARE) {
    return fp_square(a);
  }
  if (opcode == FP_OP_TO_MONT) {
    return fp_mul(a, fp_rsquare_regular());
  }
  if (opcode == FP_OP_FROM_MONT) {
    return fp_mul(a, fp_one_regular());
  }
  return fp_zero();
}

fn fp_load_a(index: u32) -> Fp {
  let base = index * 12u;
  var z: Fp;
  z.limbs[0] = input_a[base + 0u];
  z.limbs[1] = input_a[base + 1u];
  z.limbs[2] = input_a[base + 2u];
  z.limbs[3] = input_a[base + 3u];
  z.limbs[4] = input_a[base + 4u];
  z.limbs[5] = input_a[base + 5u];
  z.limbs[6] = input_a[base + 6u];
  z.limbs[7] = input_a[base + 7u];
  z.limbs[8] = input_a[base + 8u];
  z.limbs[9] = input_a[base + 9u];
  z.limbs[10] = input_a[base + 10u];
  z.limbs[11] = input_a[base + 11u];
  return z;
}

fn fp_load_b(index: u32) -> Fp {
  let base = index * 12u;
  var z: Fp;
  z.limbs[0] = input_b[base + 0u];
  z.limbs[1] = input_b[base + 1u];
  z.limbs[2] = input_b[base + 2u];
  z.limbs[3] = input_b[base + 3u];
  z.limbs[4] = input_b[base + 4u];
  z.limbs[5] = input_b[base + 5u];
  z.limbs[6] = input_b[base + 6u];
  z.limbs[7] = input_b[base + 7u];
  z.limbs[8] = input_b[base + 8u];
  z.limbs[9] = input_b[base + 9u];
  z.limbs[10] = input_b[base + 10u];
  z.limbs[11] = input_b[base + 11u];
  return z;
}

fn fp_store(index: u32, value: Fp) {
  let base = index * 12u;
  output[base + 0u] = value.limbs[0];
  output[base + 1u] = value.limbs[1];
  output[base + 2u] = value.limbs[2];
  output[base + 3u] = value.limbs[3];
  output[base + 4u] = value.limbs[4];
  output[base + 5u] = value.limbs[5];
  output[base + 6u] = value.limbs[6];
  output[base + 7u] = value.limbs[7];
  output[base + 8u] = value.limbs[8];
  output[base + 9u] = value.limbs[9];
  output[base + 10u] = value.limbs[10];
  output[base + 11u] = value.limbs[11];
}

override WORKGROUP_SIZE: u32 = 64;

@compute @workgroup_size(WORKGROUP_SIZE)
fn fp_ops_main(@builtin(global_invocation_id) id: vec3<u32>) {
  let i = id.x;
  if (i >= params.count) {
    return;
  }
  fp_store(i, fp_dispatch(params.opcode, fp_load_a(i), fp_load_b(i)));
}
