// Code generated by gnark DO NOT EDIT

struct Fr {
  limbs: array<u32, 8>,
}

// One dispatch performs `stage_count` consecutive radix-2 DIT stages
// starting at `first_stage`, on all vectors of a batch at once.
//
// Stage s pairs the elements whose flat indices differ only in bit s, with
// twiddle omega^(j << (log_n - 1 - s)) where j = index mod 2^s. The stages
// first_stage .. first_stage + stage_count - 1 therefore only mix elements
// whose indices agree outside bits [first_stage, first_stage + stage_count):
// each such "group" of 2^stage_count elements is loaded into workgroup
// memory, transformed with a barrier between stages, and written back. A
// workgroup holds 2 * WORKGROUP_SIZE elements, i.e. one butterfly per thread
// per stage, and handles several groups when the group is smaller.
//
// The load and store phases optionally fold in the neighbouring element-wise
// passes: bit-reversal of the input index (per vector) and multiplications by
// constants (Montgomery conversions, 1/n, coset denominators).
struct Params {
  // total number of elements (vector count * vector size)
  count: u32,
  first_stage: u32,
  // 0 .. log2(2 * WORKGROUP_SIZE); 0 performs the load/store phases only
  stage_count: u32,
  // bit 0: read input at bit-reversed index; bit 1: multiply loaded values by
  // load_scale; bit 2: multiply stored values by store_scale; bit 3: inverse
  // transform (twiddles are omega^-e = -omega^(n/2 - e)).
  flags: u32,
  // log2 of the vector size
  log_n: u32,
  _pad0: u32,
  _pad1: u32,
  _pad2: u32,
  load_scale: array<vec4<u32>, 2>,
  store_scale: array<vec4<u32>, 2>,
}

const NTT_FLAG_BIT_REVERSE: u32 = 1u;
const NTT_FLAG_LOAD_SCALE: u32 = 2u;
const NTT_FLAG_STORE_SCALE: u32 = 4u;
const NTT_FLAG_INVERSE: u32 = 8u;

const FR_LIMB16_MASK: u32 = 0xffffu;
const FR_QINV_NEG_16: u32 = 0xffffu;

const FR_MODULUS32: array<u32, 8> = array<u32, 8>(
  0x00000001u,
  0x0a118000u,
  0xd0000001u,
  0x59aa76feu,
  0x5c37b001u,
  0x60b44d1eu,
  0x9a2ca556u,
  0x12ab655eu,
);

const FR_MODULUS16: array<u32, 16> = array<u32, 16>(
  0x0001u, 0x0000u,
  0x8000u, 0x0a11u,
  0x0001u, 0xd000u,
  0x76feu, 0x59aau,
  0xb001u, 0x5c37u,
  0x4d1eu, 0x60b4u,
  0xa556u, 0x9a2cu,
  0x655eu, 0x12abu,
);

@group(0) @binding(0) var<storage, read> input_values: array<u32>;
// omega^i for i < n/2 (Montgomery form)
@group(0) @binding(1) var<storage, read> input_twiddles: array<u32>;
@group(0) @binding(2) var<storage, read_write> output: array<u32>;
@group(0) @binding(3) var<uniform> params: Params;

fn fr_zero() -> Fr {
  var z: Fr;
  z.limbs[0] = 0u;
  z.limbs[1] = 0u;
  z.limbs[2] = 0u;
  z.limbs[3] = 0u;
  z.limbs[4] = 0u;
  z.limbs[5] = 0u;
  z.limbs[6] = 0u;
  z.limbs[7] = 0u;
  return z;
}

fn fr_one() -> Fr {
  var z: Fr;
  z.limbs[0] = 0xfffffff3u;
  z.limbs[1] = 0x7d1c7fffu;
  z.limbs[2] = 0x6ffffff2u;
  z.limbs[3] = 0x7257f50fu;
  z.limbs[4] = 0x512c0feeu;
  z.limbs[5] = 0x16d81575u;
  z.limbs[6] = 0x2bbb9a9du;
  z.limbs[7] = 0x0d4bda32u;
  return z;
}

fn fr_one_regular() -> Fr {
  var z = fr_zero();
  z.limbs[0] = 1u;
  return z;
}

fn fr_rsquare_regular() -> Fr {
  var z: Fr;
  z.limbs[0] = 0xb861857bu;
  z.limbs[1] = 0x25d577bau;
  z.limbs[2] = 0x8860591fu;
  z.limbs[3] = 0xcc2c27b5u;
  z.limbs[4] = 0xe5dc8593u;
  z.limbs[5] = 0xa7cc008fu;
  z.limbs[6] = 0xeff1c939u;
  z.limbs[7] = 0x011fdae7u;
  return z;
}

fn fr_predicate(value: bool) -> Fr {
  let one = fr_one();
  var z: Fr;
  z.limbs[0] = select(0u, one.limbs[0], value);
  z.limbs[1] = select(0u, one.limbs[1], value);
  z.limbs[2] = select(0u, one.limbs[2], value);
  z.limbs[3] = select(0u, one.limbs[3], value);
  z.limbs[4] = select(0u, one.limbs[4], value);
  z.limbs[5] = select(0u, one.limbs[5], value);
  z.limbs[6] = select(0u, one.limbs[6], value);
  z.limbs[7] = select(0u, one.limbs[7], value);
  return z;
}

fn adc(a: u32, b: u32, carry: u32) -> vec2<u32> {
  let sum0 = a + b;
  let sum1 = sum0 + carry;
  return vec2<u32>(sum1, u32(sum0 < a) | u32(sum1 < sum0));
}

fn sbb(a: u32, b: u32, borrow: u32) -> vec2<u32> {
  let diff0 = a - b;
  let diff1 = diff0 - borrow;
  return vec2<u32>(diff1, u32(a < b) | u32(diff1 > diff0));
}

fn fr_is_zero(x: Fr) -> bool {
  return (x.limbs[0] | x.limbs[1] | x.limbs[2] | x.limbs[3] |
    x.limbs[4] | x.limbs[5] | x.limbs[6] | x.limbs[7]) == 0u;
}

fn fr_equal(x: Fr, y: Fr) -> bool {
  return (x.limbs[0] == y.limbs[0]) &&
    (x.limbs[1] == y.limbs[1]) &&
    (x.limbs[2] == y.limbs[2]) &&
    (x.limbs[3] == y.limbs[3]) &&
    (x.limbs[4] == y.limbs[4]) &&
    (x.limbs[5] == y.limbs[5]) &&
    (x.limbs[6] == y.limbs[6]) &&
    (x.limbs[7] == y.limbs[7]);
}

// x + y mod q: z = x + y, t = z - q; the result is t when the addition
// carried or the subtraction did not borrow (z >= q), else z.
fn fr_add(x: Fr, y: Fr) -> Fr {
  var z: Fr;
  var t: Fr;
  var lane = adc(x.limbs[0], y.limbs[0], 0u);
  z.limbs[0] = lane.x;
  lane = adc(x.limbs[1], y.limbs[1], lane.y);
  z.limbs[1] = lane.x;
  lane = adc(x.limbs[2], y.limbs[2], lane.y);
  z.limbs[2] = lane.x;
  lane = adc(x.limbs[3], y.limbs[3], lane.y);
  z.limbs[3] = lane.x;
  lane = adc(x.limbs[4], y.limbs[4], lane.y);
  z.limbs[4] = lane.x;
  lane = adc(x.limbs[5], y.limbs[5], lane.y);
  z.limbs[5] = lane.x;
  lane = adc(x.limbs[6], y.limbs[6], lane.y);
  z.limbs[6] = lane.x;
  lane = adc(x.limbs[7], y.limbs[7], lane.y);
  z.limbs[7] = lane.x;
  let carry = lane.y;
  lane = sbb(z.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(z.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(z.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(z.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(z.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(z.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(z.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(z.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  let use_t = (carry != 0u) || (lane.y == 0u);
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  return z;
}

// x - y mod q: z = x - y, t = z + q; the result is t when the subtraction
// borrowed, else z.
fn fr_sub(x: Fr, y: Fr) -> Fr {
  var z: Fr;
  var t: Fr;
  var lane = sbb(x.limbs[0], y.limbs[0], 0u);
  z.limbs[0] = lane.x;
  lane = sbb(x.limbs[1], y.limbs[1], lane.y);
  z.limbs[1] = lane.x;
  lane = sbb(x.limbs[2], y.limbs[2], lane.y);
  z.limbs[2] = lane.x;
  lane = sbb(x.limbs[3], y.limbs[3], lane.y);
  z.limbs[3] = lane.x;
  lane = sbb(x.limbs[4], y.limbs[4], lane.y);
  z.limbs[4] = lane.x;
  lane = sbb(x.limbs[5], y.limbs[5], lane.y);
  z.limbs[5] = lane.x;
  lane = sbb(x.limbs[6], y.limbs[6], lane.y);
  z.limbs[6] = lane.x;
  lane = sbb(x.limbs[7], y.limbs[7], lane.y);
  z.limbs[7] = lane.x;
  let use_t = lane.y != 0u;
  lane = adc(z.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = adc(z.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = adc(z.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = adc(z.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = adc(z.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = adc(z.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = adc(z.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = adc(z.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  return z;
}

// -x mod q: q - x, or zero when x is zero.
fn fr_neg(x: Fr) -> Fr {
  var t: Fr;
  var lane = sbb(FR_MODULUS32[0], x.limbs[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(FR_MODULUS32[1], x.limbs[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(FR_MODULUS32[2], x.limbs[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(FR_MODULUS32[3], x.limbs[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(FR_MODULUS32[4], x.limbs[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(FR_MODULUS32[5], x.limbs[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(FR_MODULUS32[6], x.limbs[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(FR_MODULUS32[7], x.limbs[7], lane.y);
  t.limbs[7] = lane.x;
  let nonzero = !fr_is_zero(x);
  var z: Fr;
  z.limbs[0] = select(0u, t.limbs[0], nonzero);
  z.limbs[1] = select(0u, t.limbs[1], nonzero);
  z.limbs[2] = select(0u, t.limbs[2], nonzero);
  z.limbs[3] = select(0u, t.limbs[3], nonzero);
  z.limbs[4] = select(0u, t.limbs[4], nonzero);
  z.limbs[5] = select(0u, t.limbs[5], nonzero);
  z.limbs[6] = select(0u, t.limbs[6], nonzero);
  z.limbs[7] = select(0u, t.limbs[7], nonzero);
  return z;
}

// 2x mod q: a left shift by one bit, then the same conditional subtraction
// as fr_add.
fn fr_double(x: Fr) -> Fr {
  var z: Fr;
  var t: Fr;
  z.limbs[0] = x.limbs[0] << 1u;
  z.limbs[1] = (x.limbs[1] << 1u) | (x.limbs[0] >> 31u);
  z.limbs[2] = (x.limbs[2] << 1u) | (x.limbs[1] >> 31u);
  z.limbs[3] = (x.limbs[3] << 1u) | (x.limbs[2] >> 31u);
  z.limbs[4] = (x.limbs[4] << 1u) | (x.limbs[3] >> 31u);
  z.limbs[5] = (x.limbs[5] << 1u) | (x.limbs[4] >> 31u);
  z.limbs[6] = (x.limbs[6] << 1u) | (x.limbs[5] >> 31u);
  z.limbs[7] = (x.limbs[7] << 1u) | (x.limbs[6] >> 31u);
  let carry = x.limbs[7] >> 31u;
  var lane: vec2<u32>;
  lane = sbb(z.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(z.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(z.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(z.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(z.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(z.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(z.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(z.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  let use_t = (carry != 0u) || (lane.y == 0u);
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  return z;
}

// Reduce a value in [0, 2q) to [0, q).
fn fr_normalize(x: Fr) -> Fr {
  var t: Fr;
  var z: Fr;
  var lane: vec2<u32>;
  lane = sbb(x.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(x.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(x.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(x.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(x.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(x.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(x.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(x.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  let use_t = lane.y == 0u;
  z.limbs[0] = select(x.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(x.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(x.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(x.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(x.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(x.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(x.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(x.limbs[7], t.limbs[7], use_t);
  return z;
}

// Montgomery multiplication (CIOS) over 16-bit digits: R = 2^(16*16).
// Each 16x16 partial product plus carries fits in a u32 without overflow.
// The digit loops are unrolled so the accumulator lives in registers; the
// final conditional subtraction is branch-free.
fn fr_mul(x: Fr, y: Fr) -> Fr {
  let a0 = x.limbs[0] & FR_LIMB16_MASK;
  let a1 = x.limbs[0] >> 16u;
  let a2 = x.limbs[1] & FR_LIMB16_MASK;
  let a3 = x.limbs[1] >> 16u;
  let a4 = x.limbs[2] & FR_LIMB16_MASK;
  let a5 = x.limbs[2] >> 16u;
  let a6 = x.limbs[3] & FR_LIMB16_MASK;
  let a7 = x.limbs[3] >> 16u;
  let a8 = x.limbs[4] & FR_LIMB16_MASK;
  let a9 = x.limbs[4] >> 16u;
  let a10 = x.limbs[5] & FR_LIMB16_MASK;
  let a11 = x.limbs[5] >> 16u;
  let a12 = x.limbs[6] & FR_LIMB16_MASK;
  let a13 = x.limbs[6] >> 16u;
  let a14 = x.limbs[7] & FR_LIMB16_MASK;
  let a15 = x.limbs[7] >> 16u;
  var t0 = 0u;
  var t1 = 0u;
  var t2 = 0u;
  var t3 = 0u;
  var t4 = 0u;
  var t5 = 0u;
  var t6 = 0u;
  var t7 = 0u;
  var t8 = 0u;
  var t9 = 0u;
  var t10 = 0u;
  var t11 = 0u;
  var t12 = 0u;
  var t13 = 0u;
  var t14 = 0u;
  var t15 = 0u;
  var t16 = 0u;
  var uv = 0u;
  var c = 0u;
  var m = 0u;
  for (var i = 0u; i < 8u; i = i + 1u) {
    let w = y.limbs[i];
    let b_lo = w & FR_LIMB16_MASK;
    let b_hi = w >> 16u;
    uv = t0 + a0 * b_lo;
    t0 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t1 + a1 * b_lo + c;
    t1 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + a2 * b_lo + c;
    t2 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + a3 * b_lo + c;
    t3 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + a4 * b_lo + c;
    t4 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + a5 * b_lo + c;
    t5 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + a6 * b_lo + c;
    t6 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + a7 * b_lo + c;
    t7 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + a8 * b_lo + c;
    t8 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + a9 * b_lo + c;
    t9 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + a10 * b_lo + c;
    t10 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + a11 * b_lo + c;
    t11 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + a12 * b_lo + c;
    t12 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + a13 * b_lo + c;
    t13 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + a14 * b_lo + c;
    t14 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + a15 * b_lo + c;
    t15 = uv & FR_LIMB16_MASK;
    t16 = uv >> 16u;
    m = (t0 * FR_QINV_NEG_16) & FR_LIMB16_MASK;
    // (t0 + m*q0) is 0 mod 2^16 by construction: only its carry survives.
    c = (t0 + m * FR_MODULUS16[0]) >> 16u;
    uv = t1 + m * FR_MODULUS16[1] + c;
    t0 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + m * FR_MODULUS16[2] + c;
    t1 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + m * FR_MODULUS16[3] + c;
    t2 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + m * FR_MODULUS16[4] + c;
    t3 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + m * FR_MODULUS16[5] + c;
    t4 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + m * FR_MODULUS16[6] + c;
    t5 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + m * FR_MODULUS16[7] + c;
    t6 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + m * FR_MODULUS16[8] + c;
    t7 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + m * FR_MODULUS16[9] + c;
    t8 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + m * FR_MODULUS16[10] + c;
    t9 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + m * FR_MODULUS16[11] + c;
    t10 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + m * FR_MODULUS16[12] + c;
    t11 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + m * FR_MODULUS16[13] + c;
    t12 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + m * FR_MODULUS16[14] + c;
    t13 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + m * FR_MODULUS16[15] + c;
    t14 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t16 + c;
    t15 = uv & FR_LIMB16_MASK;
    t16 = uv >> 16u;
    uv = t0 + a0 * b_hi;
    t0 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t1 + a1 * b_hi + c;
    t1 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + a2 * b_hi + c;
    t2 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + a3 * b_hi + c;
    t3 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + a4 * b_hi + c;
    t4 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + a5 * b_hi + c;
    t5 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + a6 * b_hi + c;
    t6 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + a7 * b_hi + c;
    t7 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + a8 * b_hi + c;
    t8 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + a9 * b_hi + c;
    t9 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + a10 * b_hi + c;
    t10 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + a11 * b_hi + c;
    t11 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + a12 * b_hi + c;
    t12 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + a13 * b_hi + c;
    t13 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + a14 * b_hi + c;
    t14 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + a15 * b_hi + c;
    t15 = uv & FR_LIMB16_MASK;
    t16 = uv >> 16u;
    m = (t0 * FR_QINV_NEG_16) & FR_LIMB16_MASK;
    // (t0 + m*q0) is 0 mod 2^16 by construction: only its carry survives.
    c = (t0 + m * FR_MODULUS16[0]) >> 16u;
    uv = t1 + m * FR_MODULUS16[1] + c;
    t0 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t2 + m * FR_MODULUS16[2] + c;
    t1 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t3 + m * FR_MODULUS16[3] + c;
    t2 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t4 + m * FR_MODULUS16[4] + c;
    t3 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t5 + m * FR_MODULUS16[5] + c;
    t4 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t6 + m * FR_MODULUS16[6] + c;
    t5 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t7 + m * FR_MODULUS16[7] + c;
    t6 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t8 + m * FR_MODULUS16[8] + c;
    t7 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t9 + m * FR_MODULUS16[9] + c;
    t8 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t10 + m * FR_MODULUS16[10] + c;
    t9 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t11 + m * FR_MODULUS16[11] + c;
    t10 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t12 + m * FR_MODULUS16[12] + c;
    t11 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t13 + m * FR_MODULUS16[13] + c;
    t12 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t14 + m * FR_MODULUS16[14] + c;
    t13 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t15 + m * FR_MODULUS16[15] + c;
    t14 = uv & FR_LIMB16_MASK;
    c = uv >> 16u;
    uv = t16 + c;
    t15 = uv & FR_LIMB16_MASK;
    t16 = uv >> 16u;
  }

  var z: Fr;
  z.limbs[0] = t0 | (t1 << 16u);
  z.limbs[1] = t2 | (t3 << 16u);
  z.limbs[2] = t4 | (t5 << 16u);
  z.limbs[3] = t6 | (t7 << 16u);
  z.limbs[4] = t8 | (t9 << 16u);
  z.limbs[5] = t10 | (t11 << 16u);
  z.limbs[6] = t12 | (t13 << 16u);
  z.limbs[7] = t14 | (t15 << 16u);
  var t: Fr;
  var lane: vec2<u32>;
  lane = sbb(z.limbs[0], FR_MODULUS32[0], 0u);
  t.limbs[0] = lane.x;
  lane = sbb(z.limbs[1], FR_MODULUS32[1], lane.y);
  t.limbs[1] = lane.x;
  lane = sbb(z.limbs[2], FR_MODULUS32[2], lane.y);
  t.limbs[2] = lane.x;
  lane = sbb(z.limbs[3], FR_MODULUS32[3], lane.y);
  t.limbs[3] = lane.x;
  lane = sbb(z.limbs[4], FR_MODULUS32[4], lane.y);
  t.limbs[4] = lane.x;
  lane = sbb(z.limbs[5], FR_MODULUS32[5], lane.y);
  t.limbs[5] = lane.x;
  lane = sbb(z.limbs[6], FR_MODULUS32[6], lane.y);
  t.limbs[6] = lane.x;
  lane = sbb(z.limbs[7], FR_MODULUS32[7], lane.y);
  t.limbs[7] = lane.x;
  let use_t = (t16 != 0u) || (lane.y == 0u);
  z.limbs[0] = select(z.limbs[0], t.limbs[0], use_t);
  z.limbs[1] = select(z.limbs[1], t.limbs[1], use_t);
  z.limbs[2] = select(z.limbs[2], t.limbs[2], use_t);
  z.limbs[3] = select(z.limbs[3], t.limbs[3], use_t);
  z.limbs[4] = select(z.limbs[4], t.limbs[4], use_t);
  z.limbs[5] = select(z.limbs[5], t.limbs[5], use_t);
  z.limbs[6] = select(z.limbs[6], t.limbs[6], use_t);
  z.limbs[7] = select(z.limbs[7], t.limbs[7], use_t);
  return z;
}

fn fr_square(x: Fr) -> Fr {
  return fr_mul(x, x);
}

fn fr_from_uniform(words: array<vec4<u32>, 2>) -> Fr {
  var z: Fr;
  z.limbs[0] = words[0][0];
  z.limbs[1] = words[0][1];
  z.limbs[2] = words[0][2];
  z.limbs[3] = words[0][3];
  z.limbs[4] = words[1][0];
  z.limbs[5] = words[1][1];
  z.limbs[6] = words[1][2];
  z.limbs[7] = words[1][3];
  return z;
}

fn fr_load(index: u32) -> Fr {
  let base = index * 8u;
  var z: Fr;
  z.limbs[0] = input_values[base + 0u];
  z.limbs[1] = input_values[base + 1u];
  z.limbs[2] = input_values[base + 2u];
  z.limbs[3] = input_values[base + 3u];
  z.limbs[4] = input_values[base + 4u];
  z.limbs[5] = input_values[base + 5u];
  z.limbs[6] = input_values[base + 6u];
  z.limbs[7] = input_values[base + 7u];
  return z;
}

fn fr_load_twiddle(index: u32) -> Fr {
  let base = index * 8u;
  var z: Fr;
  z.limbs[0] = input_twiddles[base + 0u];
  z.limbs[1] = input_twiddles[base + 1u];
  z.limbs[2] = input_twiddles[base + 2u];
  z.limbs[3] = input_twiddles[base + 3u];
  z.limbs[4] = input_twiddles[base + 4u];
  z.limbs[5] = input_twiddles[base + 5u];
  z.limbs[6] = input_twiddles[base + 6u];
  z.limbs[7] = input_twiddles[base + 7u];
  return z;
}

fn fr_store(index: u32, value: Fr) {
  let base = index * 8u;
  output[base + 0u] = value.limbs[0];
  output[base + 1u] = value.limbs[1];
  output[base + 2u] = value.limbs[2];
  output[base + 3u] = value.limbs[3];
  output[base + 4u] = value.limbs[4];
  output[base + 5u] = value.limbs[5];
  output[base + 6u] = value.limbs[6];
  output[base + 7u] = value.limbs[7];
}

// omega^exponent (forward) or omega^-exponent (inverse) for exponent < n/2,
// from the half table: omega^-e = omega^(n/2) * omega^(n/2 - e) = -omega^(n/2 - e).
fn fr_twiddle(exponent: u32, inverse: bool) -> Fr {
  if (!inverse) {
    return fr_load_twiddle(exponent);
  }
  let half_mask = (1u << (params.log_n - 1u)) - 1u;
  // (n/2 - e) mod n/2 is 0 for e = 0, where the twiddle is 1 rather than -1.
  let value = fr_load_twiddle((0u - exponent) & half_mask);
  let negated = fr_neg(value);
  var z: Fr;
  z.limbs[0] = select(negated.limbs[0], value.limbs[0], exponent == 0u);
  z.limbs[1] = select(negated.limbs[1], value.limbs[1], exponent == 0u);
  z.limbs[2] = select(negated.limbs[2], value.limbs[2], exponent == 0u);
  z.limbs[3] = select(negated.limbs[3], value.limbs[3], exponent == 0u);
  z.limbs[4] = select(negated.limbs[4], value.limbs[4], exponent == 0u);
  z.limbs[5] = select(negated.limbs[5], value.limbs[5], exponent == 0u);
  z.limbs[6] = select(negated.limbs[6], value.limbs[6], exponent == 0u);
  z.limbs[7] = select(negated.limbs[7], value.limbs[7], exponent == 0u);
  return z;
}

override WORKGROUP_SIZE: u32 = 256;

// 2 * WORKGROUP_SIZE elements: one radix-2 butterfly per thread per stage.
var<workgroup> tile: array<Fr, 2 * WORKGROUP_SIZE>;

// Flat element index of tile slot `slot` (see the header comment): the
// group's index has `stage_count` zero bits inserted at `first_stage`, and the
// position inside the group fills those bits.
fn tile_index(slot: u32, first_group: u32) -> u32 {
  let k = params.stage_count;
  let s0 = params.first_stage;
  let group = first_group + (slot >> k);
  let position = slot & ((1u << k) - 1u);
  let base = ((group >> s0) << (s0 + k)) | (group & ((1u << s0) - 1u));
  return base | (position << s0);
}

@compute @workgroup_size(WORKGROUP_SIZE)
fn fr_ntt_fused_main(
  @builtin(local_invocation_id) local_id: vec3<u32>,
  @builtin(workgroup_id) workgroup_id: vec3<u32>,
  @builtin(num_workgroups) num_workgroups: vec3<u32>,
) {
  let tid = local_id.x;
  let workgroup_index = workgroup_id.x + workgroup_id.y * num_workgroups.x;
  let k = params.stage_count;
  let s0 = params.first_stage;
  let log_n = params.log_n;
  let n_mask = (1u << log_n) - 1u;
  let inverse = (params.flags & NTT_FLAG_INVERSE) != 0u;
  let tile_elements = 2u * WORKGROUP_SIZE;
  let first_group = workgroup_index * (tile_elements >> k);

  // Load 2 * WORKGROUP_SIZE elements (two per thread) into the tile.
  for (var slot = tid; slot < tile_elements; slot = slot + WORKGROUP_SIZE) {
    let index = tile_index(slot, first_group);
    var value = fr_zero();
    if (index < params.count) {
      var source = index;
      if ((params.flags & NTT_FLAG_BIT_REVERSE) != 0u) {
        let lane = index & n_mask;
        source = (index - lane) | (reverseBits(lane) >> min(32u - log_n, 31u));
      }
      value = fr_load(source);
      if ((params.flags & NTT_FLAG_LOAD_SCALE) != 0u) {
        value = fr_mul(value, fr_from_uniform(params.load_scale));
      }
    }
    tile[slot] = value;
  }
  workgroupBarrier();

  // Butterfly stages: thread `tid` owns butterfly `tid mod half` of local
  // group `tid / half`, where half = 2^(k-1) butterflies per group per stage.
  for (var local_stage = 0u; local_stage < k; local_stage = local_stage + 1u) {
    let stage = s0 + local_stage;
    let half = 1u << (k - 1u);
    let local_group = tid >> (k - 1u);
    let butterfly = tid & (half - 1u);
    let m = 1u << local_stage;
    let j_local = butterfly & (m - 1u);
    let left_position = ((butterfly >> local_stage) << (local_stage + 1u)) | j_local;
    let left_slot = (local_group << k) | left_position;
    let right_slot = left_slot | m;

    let left = tile[left_slot];
    var right = tile[right_slot];
    if (stage != 0u) {
      // twiddle index j = flat index mod 2^stage = low s0 bits of the group | j_local << s0
      let group = first_group + local_group;
      let j = (group & ((1u << s0) - 1u)) | (j_local << s0);
      right = fr_mul(right, fr_twiddle(j << (log_n - 1u - stage), inverse));
    }
    tile[left_slot] = fr_add(left, right);
    tile[right_slot] = fr_sub(left, right);
    workgroupBarrier();
  }

  for (var slot = tid; slot < tile_elements; slot = slot + WORKGROUP_SIZE) {
    let index = tile_index(slot, first_group);
    if (index < params.count) {
      var value = tile[slot];
      if ((params.flags & NTT_FLAG_STORE_SCALE) != 0u) {
        value = fr_mul(value, fr_from_uniform(params.store_scale));
      }
      fr_store(index, value);
    }
  }
}
